all: false
template: testify
formatter: goimports
packages:
  github.com/wigata-intech/logres/internal/api/repository:
    config:
      inpackage: false
      dir: "mock/api/repository"
      filename: "{{.InterfaceName}}.go"
    interfaces:
      IAdminUserRepository:
      IAdminPasswordResetRepository:
      IAdminRefreshTokenRepository:
      ICartRepository:
      ICategoryRepository:
      IFileRepository:
      IOrderRepository:
      IProductRepository:
      ITagRepository:
  github.com/wigata-intech/logres/internal/api/service:
    config:
      inpackage: false
      dir: "mock/api/service"
      filename: "{{.InterfaceName}}.go"
    interfaces:
      IAdminUserService:
      IAdminFileService:
      IAdminProductService:
      IAdminOrderService:
      IProductService:
      ICartService:
      IOrderService:
  github.com/wigata-intech/logres/internal/shared/mailer:
    config:
      inpackage: false
      dir: "mock/shared/mailer"
      filename: "{{.InterfaceName}}.go"
    interfaces:
      Mailer: