// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package repository

import (
	"context"

	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
	"github.com/wigata-intech/logres/internal/api/model"
)

// NewMockIAdminPasswordResetRepository creates a new instance of MockIAdminPasswordResetRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIAdminPasswordResetRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIAdminPasswordResetRepository {
	mock := &MockIAdminPasswordResetRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockIAdminPasswordResetRepository is an autogenerated mock type for the IAdminPasswordResetRepository type
type MockIAdminPasswordResetRepository struct {
	mock.Mock
}

type MockIAdminPasswordResetRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIAdminPasswordResetRepository) EXPECT() *MockIAdminPasswordResetRepository_Expecter {
	return &MockIAdminPasswordResetRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockIAdminPasswordResetRepository
func (_mock *MockIAdminPasswordResetRepository) Create(ctx context.Context, reset *model.AdminPasswordReset) error {
	ret := _mock.Called(ctx, reset)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *model.AdminPasswordReset) error); ok {
		r0 = returnFunc(ctx, reset)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIAdminPasswordResetRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockIAdminPasswordResetRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - reset *model.AdminPasswordReset
func (_e *MockIAdminPasswordResetRepository_Expecter) Create(ctx any, reset any) *MockIAdminPasswordResetRepository_Create_Call {
	return &MockIAdminPasswordResetRepository_Create_Call{Call: _e.mock.On("Create", ctx, reset)}
}

func (_c *MockIAdminPasswordResetRepository_Create_Call) Run(run func(ctx context.Context, reset *model.AdminPasswordReset)) *MockIAdminPasswordResetRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *model.AdminPasswordReset
		if args[1] != nil {
			arg1 = args[1].(*model.AdminPasswordReset)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIAdminPasswordResetRepository_Create_Call) Return(err error) *MockIAdminPasswordResetRepository_Create_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIAdminPasswordResetRepository_Create_Call) RunAndReturn(run func(ctx context.Context, reset *model.AdminPasswordReset) error) *MockIAdminPasswordResetRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// GetActiveByUser provides a mock function for the type MockIAdminPasswordResetRepository
func (_mock *MockIAdminPasswordResetRepository) GetActiveByUser(ctx context.Context, adminUserID uuid.UUID, purpose string) (*model.AdminPasswordReset, error) {
	ret := _mock.Called(ctx, adminUserID, purpose)

	if len(ret) == 0 {
		panic("no return value specified for GetActiveByUser")
	}

	var r0 *model.AdminPasswordReset
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, string) (*model.AdminPasswordReset, error)); ok {
		return returnFunc(ctx, adminUserID, purpose)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, string) *model.AdminPasswordReset); ok {
		r0 = returnFunc(ctx, adminUserID, purpose)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.AdminPasswordReset)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, string) error); ok {
		r1 = returnFunc(ctx, adminUserID, purpose)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIAdminPasswordResetRepository_GetActiveByUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetActiveByUser'
type MockIAdminPasswordResetRepository_GetActiveByUser_Call struct {
	*mock.Call
}

// GetActiveByUser is a helper method to define mock.On call
//   - ctx context.Context
//   - adminUserID uuid.UUID
//   - purpose string
func (_e *MockIAdminPasswordResetRepository_Expecter) GetActiveByUser(ctx any, adminUserID any, purpose any) *MockIAdminPasswordResetRepository_GetActiveByUser_Call {
	return &MockIAdminPasswordResetRepository_GetActiveByUser_Call{Call: _e.mock.On("GetActiveByUser", ctx, adminUserID, purpose)}
}

func (_c *MockIAdminPasswordResetRepository_GetActiveByUser_Call) Run(run func(ctx context.Context, adminUserID uuid.UUID, purpose string)) *MockIAdminPasswordResetRepository_GetActiveByUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockIAdminPasswordResetRepository_GetActiveByUser_Call) Return(adminPasswordReset *model.AdminPasswordReset, err error) *MockIAdminPasswordResetRepository_GetActiveByUser_Call {
	_c.Call.Return(adminPasswordReset, err)
	return _c
}

func (_c *MockIAdminPasswordResetRepository_GetActiveByUser_Call) RunAndReturn(run func(ctx context.Context, adminUserID uuid.UUID, purpose string) (*model.AdminPasswordReset, error)) *MockIAdminPasswordResetRepository_GetActiveByUser_Call {
	_c.Call.Return(run)
	return _c
}

// IncrementAttempt provides a mock function for the type MockIAdminPasswordResetRepository
func (_mock *MockIAdminPasswordResetRepository) IncrementAttempt(ctx context.Context, id uuid.UUID) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for IncrementAttempt")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIAdminPasswordResetRepository_IncrementAttempt_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IncrementAttempt'
type MockIAdminPasswordResetRepository_IncrementAttempt_Call struct {
	*mock.Call
}

// IncrementAttempt is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockIAdminPasswordResetRepository_Expecter) IncrementAttempt(ctx any, id any) *MockIAdminPasswordResetRepository_IncrementAttempt_Call {
	return &MockIAdminPasswordResetRepository_IncrementAttempt_Call{Call: _e.mock.On("IncrementAttempt", ctx, id)}
}

func (_c *MockIAdminPasswordResetRepository_IncrementAttempt_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockIAdminPasswordResetRepository_IncrementAttempt_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIAdminPasswordResetRepository_IncrementAttempt_Call) Return(err error) *MockIAdminPasswordResetRepository_IncrementAttempt_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIAdminPasswordResetRepository_IncrementAttempt_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID) error) *MockIAdminPasswordResetRepository_IncrementAttempt_Call {
	_c.Call.Return(run)
	return _c
}

// InvalidateAllForUser provides a mock function for the type MockIAdminPasswordResetRepository
func (_mock *MockIAdminPasswordResetRepository) InvalidateAllForUser(ctx context.Context, adminUserID uuid.UUID, purpose string) error {
	ret := _mock.Called(ctx, adminUserID, purpose)

	if len(ret) == 0 {
		panic("no return value specified for InvalidateAllForUser")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, string) error); ok {
		r0 = returnFunc(ctx, adminUserID, purpose)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIAdminPasswordResetRepository_InvalidateAllForUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InvalidateAllForUser'
type MockIAdminPasswordResetRepository_InvalidateAllForUser_Call struct {
	*mock.Call
}

// InvalidateAllForUser is a helper method to define mock.On call
//   - ctx context.Context
//   - adminUserID uuid.UUID
//   - purpose string
func (_e *MockIAdminPasswordResetRepository_Expecter) InvalidateAllForUser(ctx any, adminUserID any, purpose any) *MockIAdminPasswordResetRepository_InvalidateAllForUser_Call {
	return &MockIAdminPasswordResetRepository_InvalidateAllForUser_Call{Call: _e.mock.On("InvalidateAllForUser", ctx, adminUserID, purpose)}
}

func (_c *MockIAdminPasswordResetRepository_InvalidateAllForUser_Call) Run(run func(ctx context.Context, adminUserID uuid.UUID, purpose string)) *MockIAdminPasswordResetRepository_InvalidateAllForUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockIAdminPasswordResetRepository_InvalidateAllForUser_Call) Return(err error) *MockIAdminPasswordResetRepository_InvalidateAllForUser_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIAdminPasswordResetRepository_InvalidateAllForUser_Call) RunAndReturn(run func(ctx context.Context, adminUserID uuid.UUID, purpose string) error) *MockIAdminPasswordResetRepository_InvalidateAllForUser_Call {
	_c.Call.Return(run)
	return _c
}

// MarkUsed provides a mock function for the type MockIAdminPasswordResetRepository
func (_mock *MockIAdminPasswordResetRepository) MarkUsed(ctx context.Context, id uuid.UUID) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for MarkUsed")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIAdminPasswordResetRepository_MarkUsed_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MarkUsed'
type MockIAdminPasswordResetRepository_MarkUsed_Call struct {
	*mock.Call
}

// MarkUsed is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockIAdminPasswordResetRepository_Expecter) MarkUsed(ctx any, id any) *MockIAdminPasswordResetRepository_MarkUsed_Call {
	return &MockIAdminPasswordResetRepository_MarkUsed_Call{Call: _e.mock.On("MarkUsed", ctx, id)}
}

func (_c *MockIAdminPasswordResetRepository_MarkUsed_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockIAdminPasswordResetRepository_MarkUsed_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIAdminPasswordResetRepository_MarkUsed_Call) Return(err error) *MockIAdminPasswordResetRepository_MarkUsed_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIAdminPasswordResetRepository_MarkUsed_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID) error) *MockIAdminPasswordResetRepository_MarkUsed_Call {
	_c.Call.Return(run)
	return _c
}
