// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package repository

import (
	"context"

	mock "github.com/stretchr/testify/mock"
	"github.com/wigata-intech/logres/internal/api/model"
)

// NewMockIAdminUserRepository creates a new instance of MockIAdminUserRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIAdminUserRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIAdminUserRepository {
	mock := &MockIAdminUserRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockIAdminUserRepository is an autogenerated mock type for the IAdminUserRepository type
type MockIAdminUserRepository struct {
	mock.Mock
}

type MockIAdminUserRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIAdminUserRepository) EXPECT() *MockIAdminUserRepository_Expecter {
	return &MockIAdminUserRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockIAdminUserRepository
func (_mock *MockIAdminUserRepository) Create(ctx context.Context, adminUser model.AdminUser) error {
	ret := _mock.Called(ctx, adminUser)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, model.AdminUser) error); ok {
		r0 = returnFunc(ctx, adminUser)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIAdminUserRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockIAdminUserRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - adminUser model.AdminUser
func (_e *MockIAdminUserRepository_Expecter) Create(ctx any, adminUser any) *MockIAdminUserRepository_Create_Call {
	return &MockIAdminUserRepository_Create_Call{Call: _e.mock.On("Create", ctx, adminUser)}
}

func (_c *MockIAdminUserRepository_Create_Call) Run(run func(ctx context.Context, adminUser model.AdminUser)) *MockIAdminUserRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 model.AdminUser
		if args[1] != nil {
			arg1 = args[1].(model.AdminUser)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIAdminUserRepository_Create_Call) Return(err error) *MockIAdminUserRepository_Create_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIAdminUserRepository_Create_Call) RunAndReturn(run func(ctx context.Context, adminUser model.AdminUser) error) *MockIAdminUserRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// GetByEmail provides a mock function for the type MockIAdminUserRepository
func (_mock *MockIAdminUserRepository) GetByEmail(ctx context.Context, email string) (*model.AdminUser, error) {
	ret := _mock.Called(ctx, email)

	if len(ret) == 0 {
		panic("no return value specified for GetByEmail")
	}

	var r0 *model.AdminUser
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*model.AdminUser, error)); ok {
		return returnFunc(ctx, email)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *model.AdminUser); ok {
		r0 = returnFunc(ctx, email)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.AdminUser)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, email)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIAdminUserRepository_GetByEmail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByEmail'
type MockIAdminUserRepository_GetByEmail_Call struct {
	*mock.Call
}

// GetByEmail is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
func (_e *MockIAdminUserRepository_Expecter) GetByEmail(ctx any, email any) *MockIAdminUserRepository_GetByEmail_Call {
	return &MockIAdminUserRepository_GetByEmail_Call{Call: _e.mock.On("GetByEmail", ctx, email)}
}

func (_c *MockIAdminUserRepository_GetByEmail_Call) Run(run func(ctx context.Context, email string)) *MockIAdminUserRepository_GetByEmail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIAdminUserRepository_GetByEmail_Call) Return(adminUser *model.AdminUser, err error) *MockIAdminUserRepository_GetByEmail_Call {
	_c.Call.Return(adminUser, err)
	return _c
}

func (_c *MockIAdminUserRepository_GetByEmail_Call) RunAndReturn(run func(ctx context.Context, email string) (*model.AdminUser, error)) *MockIAdminUserRepository_GetByEmail_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type MockIAdminUserRepository
func (_mock *MockIAdminUserRepository) Update(ctx context.Context, adminUser model.AdminUser) error {
	ret := _mock.Called(ctx, adminUser)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, model.AdminUser) error); ok {
		r0 = returnFunc(ctx, adminUser)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIAdminUserRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockIAdminUserRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - adminUser model.AdminUser
func (_e *MockIAdminUserRepository_Expecter) Update(ctx any, adminUser any) *MockIAdminUserRepository_Update_Call {
	return &MockIAdminUserRepository_Update_Call{Call: _e.mock.On("Update", ctx, adminUser)}
}

func (_c *MockIAdminUserRepository_Update_Call) Run(run func(ctx context.Context, adminUser model.AdminUser)) *MockIAdminUserRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 model.AdminUser
		if args[1] != nil {
			arg1 = args[1].(model.AdminUser)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIAdminUserRepository_Update_Call) Return(err error) *MockIAdminUserRepository_Update_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIAdminUserRepository_Update_Call) RunAndReturn(run func(ctx context.Context, adminUser model.AdminUser) error) *MockIAdminUserRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}
