// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package repository

import (
	"context"

	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
	"github.com/wigata-intech/logres/internal/api/model"
)

// NewMockIAdminRefreshTokenRepository creates a new instance of MockIAdminRefreshTokenRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIAdminRefreshTokenRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIAdminRefreshTokenRepository {
	mock := &MockIAdminRefreshTokenRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockIAdminRefreshTokenRepository is an autogenerated mock type for the IAdminRefreshTokenRepository type
type MockIAdminRefreshTokenRepository struct {
	mock.Mock
}

type MockIAdminRefreshTokenRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIAdminRefreshTokenRepository) EXPECT() *MockIAdminRefreshTokenRepository_Expecter {
	return &MockIAdminRefreshTokenRepository_Expecter{mock: &_m.Mock}
}

// GetByHash provides a mock function for the type MockIAdminRefreshTokenRepository
func (_mock *MockIAdminRefreshTokenRepository) GetByHash(ctx context.Context, tokenHash string) (*model.AdminRefreshToken, error) {
	ret := _mock.Called(ctx, tokenHash)

	if len(ret) == 0 {
		panic("no return value specified for GetByHash")
	}

	var r0 *model.AdminRefreshToken
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*model.AdminRefreshToken, error)); ok {
		return returnFunc(ctx, tokenHash)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *model.AdminRefreshToken); ok {
		r0 = returnFunc(ctx, tokenHash)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.AdminRefreshToken)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, tokenHash)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIAdminRefreshTokenRepository_GetByHash_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByHash'
type MockIAdminRefreshTokenRepository_GetByHash_Call struct {
	*mock.Call
}

// GetByHash is a helper method to define mock.On call
//   - ctx context.Context
//   - tokenHash string
func (_e *MockIAdminRefreshTokenRepository_Expecter) GetByHash(ctx any, tokenHash any) *MockIAdminRefreshTokenRepository_GetByHash_Call {
	return &MockIAdminRefreshTokenRepository_GetByHash_Call{Call: _e.mock.On("GetByHash", ctx, tokenHash)}
}

func (_c *MockIAdminRefreshTokenRepository_GetByHash_Call) Run(run func(ctx context.Context, tokenHash string)) *MockIAdminRefreshTokenRepository_GetByHash_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIAdminRefreshTokenRepository_GetByHash_Call) Return(adminRefreshToken *model.AdminRefreshToken, err error) *MockIAdminRefreshTokenRepository_GetByHash_Call {
	_c.Call.Return(adminRefreshToken, err)
	return _c
}

func (_c *MockIAdminRefreshTokenRepository_GetByHash_Call) RunAndReturn(run func(ctx context.Context, tokenHash string) (*model.AdminRefreshToken, error)) *MockIAdminRefreshTokenRepository_GetByHash_Call {
	_c.Call.Return(run)
	return _c
}

// Insert provides a mock function for the type MockIAdminRefreshTokenRepository
func (_mock *MockIAdminRefreshTokenRepository) Insert(ctx context.Context, token *model.AdminRefreshToken) error {
	ret := _mock.Called(ctx, token)

	if len(ret) == 0 {
		panic("no return value specified for Insert")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *model.AdminRefreshToken) error); ok {
		r0 = returnFunc(ctx, token)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIAdminRefreshTokenRepository_Insert_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Insert'
type MockIAdminRefreshTokenRepository_Insert_Call struct {
	*mock.Call
}

// Insert is a helper method to define mock.On call
//   - ctx context.Context
//   - token *model.AdminRefreshToken
func (_e *MockIAdminRefreshTokenRepository_Expecter) Insert(ctx any, token any) *MockIAdminRefreshTokenRepository_Insert_Call {
	return &MockIAdminRefreshTokenRepository_Insert_Call{Call: _e.mock.On("Insert", ctx, token)}
}

func (_c *MockIAdminRefreshTokenRepository_Insert_Call) Run(run func(ctx context.Context, token *model.AdminRefreshToken)) *MockIAdminRefreshTokenRepository_Insert_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *model.AdminRefreshToken
		if args[1] != nil {
			arg1 = args[1].(*model.AdminRefreshToken)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIAdminRefreshTokenRepository_Insert_Call) Return(err error) *MockIAdminRefreshTokenRepository_Insert_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIAdminRefreshTokenRepository_Insert_Call) RunAndReturn(run func(ctx context.Context, token *model.AdminRefreshToken) error) *MockIAdminRefreshTokenRepository_Insert_Call {
	_c.Call.Return(run)
	return _c
}

// RevokeAllForUser provides a mock function for the type MockIAdminRefreshTokenRepository
func (_mock *MockIAdminRefreshTokenRepository) RevokeAllForUser(ctx context.Context, adminUserID uuid.UUID) error {
	ret := _mock.Called(ctx, adminUserID)

	if len(ret) == 0 {
		panic("no return value specified for RevokeAllForUser")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, adminUserID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIAdminRefreshTokenRepository_RevokeAllForUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RevokeAllForUser'
type MockIAdminRefreshTokenRepository_RevokeAllForUser_Call struct {
	*mock.Call
}

// RevokeAllForUser is a helper method to define mock.On call
//   - ctx context.Context
//   - adminUserID uuid.UUID
func (_e *MockIAdminRefreshTokenRepository_Expecter) RevokeAllForUser(ctx any, adminUserID any) *MockIAdminRefreshTokenRepository_RevokeAllForUser_Call {
	return &MockIAdminRefreshTokenRepository_RevokeAllForUser_Call{Call: _e.mock.On("RevokeAllForUser", ctx, adminUserID)}
}

func (_c *MockIAdminRefreshTokenRepository_RevokeAllForUser_Call) Run(run func(ctx context.Context, adminUserID uuid.UUID)) *MockIAdminRefreshTokenRepository_RevokeAllForUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIAdminRefreshTokenRepository_RevokeAllForUser_Call) Return(err error) *MockIAdminRefreshTokenRepository_RevokeAllForUser_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIAdminRefreshTokenRepository_RevokeAllForUser_Call) RunAndReturn(run func(ctx context.Context, adminUserID uuid.UUID) error) *MockIAdminRefreshTokenRepository_RevokeAllForUser_Call {
	_c.Call.Return(run)
	return _c
}

// RevokeFamily provides a mock function for the type MockIAdminRefreshTokenRepository
func (_mock *MockIAdminRefreshTokenRepository) RevokeFamily(ctx context.Context, familyID uuid.UUID) error {
	ret := _mock.Called(ctx, familyID)

	if len(ret) == 0 {
		panic("no return value specified for RevokeFamily")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, familyID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIAdminRefreshTokenRepository_RevokeFamily_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RevokeFamily'
type MockIAdminRefreshTokenRepository_RevokeFamily_Call struct {
	*mock.Call
}

// RevokeFamily is a helper method to define mock.On call
//   - ctx context.Context
//   - familyID uuid.UUID
func (_e *MockIAdminRefreshTokenRepository_Expecter) RevokeFamily(ctx any, familyID any) *MockIAdminRefreshTokenRepository_RevokeFamily_Call {
	return &MockIAdminRefreshTokenRepository_RevokeFamily_Call{Call: _e.mock.On("RevokeFamily", ctx, familyID)}
}

func (_c *MockIAdminRefreshTokenRepository_RevokeFamily_Call) Run(run func(ctx context.Context, familyID uuid.UUID)) *MockIAdminRefreshTokenRepository_RevokeFamily_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIAdminRefreshTokenRepository_RevokeFamily_Call) Return(err error) *MockIAdminRefreshTokenRepository_RevokeFamily_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIAdminRefreshTokenRepository_RevokeFamily_Call) RunAndReturn(run func(ctx context.Context, familyID uuid.UUID) error) *MockIAdminRefreshTokenRepository_RevokeFamily_Call {
	_c.Call.Return(run)
	return _c
}

// Rotate provides a mock function for the type MockIAdminRefreshTokenRepository
func (_mock *MockIAdminRefreshTokenRepository) Rotate(ctx context.Context, oldID uuid.UUID, newID uuid.UUID) error {
	ret := _mock.Called(ctx, oldID, newID)

	if len(ret) == 0 {
		panic("no return value specified for Rotate")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, oldID, newID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIAdminRefreshTokenRepository_Rotate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Rotate'
type MockIAdminRefreshTokenRepository_Rotate_Call struct {
	*mock.Call
}

// Rotate is a helper method to define mock.On call
//   - ctx context.Context
//   - oldID uuid.UUID
//   - newID uuid.UUID
func (_e *MockIAdminRefreshTokenRepository_Expecter) Rotate(ctx any, oldID any, newID any) *MockIAdminRefreshTokenRepository_Rotate_Call {
	return &MockIAdminRefreshTokenRepository_Rotate_Call{Call: _e.mock.On("Rotate", ctx, oldID, newID)}
}

func (_c *MockIAdminRefreshTokenRepository_Rotate_Call) Run(run func(ctx context.Context, oldID uuid.UUID, newID uuid.UUID)) *MockIAdminRefreshTokenRepository_Rotate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockIAdminRefreshTokenRepository_Rotate_Call) Return(err error) *MockIAdminRefreshTokenRepository_Rotate_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIAdminRefreshTokenRepository_Rotate_Call) RunAndReturn(run func(ctx context.Context, oldID uuid.UUID, newID uuid.UUID) error) *MockIAdminRefreshTokenRepository_Rotate_Call {
	_c.Call.Return(run)
	return _c
}
