// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package repository

import (
	"context"

	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
	"github.com/wigata-intech/logres/internal/api/model"
	model0 "github.com/wigata-intech/logres/internal/shared/model"
)

// NewMockICartRepository creates a new instance of MockICartRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockICartRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockICartRepository {
	mock := &MockICartRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockICartRepository is an autogenerated mock type for the ICartRepository type
type MockICartRepository struct {
	mock.Mock
}

type MockICartRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockICartRepository) EXPECT() *MockICartRepository_Expecter {
	return &MockICartRepository_Expecter{mock: &_m.Mock}
}

// Delete provides a mock function for the type MockICartRepository
func (_mock *MockICartRepository) Delete(ctx context.Context, cart model.Cart) error {
	ret := _mock.Called(ctx, cart)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, model.Cart) error); ok {
		r0 = returnFunc(ctx, cart)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockICartRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockICartRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - cart model.Cart
func (_e *MockICartRepository_Expecter) Delete(ctx any, cart any) *MockICartRepository_Delete_Call {
	return &MockICartRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, cart)}
}

func (_c *MockICartRepository_Delete_Call) Run(run func(ctx context.Context, cart model.Cart)) *MockICartRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 model.Cart
		if args[1] != nil {
			arg1 = args[1].(model.Cart)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockICartRepository_Delete_Call) Return(err error) *MockICartRepository_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockICartRepository_Delete_Call) RunAndReturn(run func(ctx context.Context, cart model.Cart) error) *MockICartRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// GetByIdentifierID provides a mock function for the type MockICartRepository
func (_mock *MockICartRepository) GetByIdentifierID(ctx context.Context, identifierID uuid.UUID) (*model.Cart, error) {
	ret := _mock.Called(ctx, identifierID)

	if len(ret) == 0 {
		panic("no return value specified for GetByIdentifierID")
	}

	var r0 *model.Cart
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*model.Cart, error)); ok {
		return returnFunc(ctx, identifierID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) *model.Cart); ok {
		r0 = returnFunc(ctx, identifierID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Cart)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, identifierID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockICartRepository_GetByIdentifierID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByIdentifierID'
type MockICartRepository_GetByIdentifierID_Call struct {
	*mock.Call
}

// GetByIdentifierID is a helper method to define mock.On call
//   - ctx context.Context
//   - identifierID uuid.UUID
func (_e *MockICartRepository_Expecter) GetByIdentifierID(ctx any, identifierID any) *MockICartRepository_GetByIdentifierID_Call {
	return &MockICartRepository_GetByIdentifierID_Call{Call: _e.mock.On("GetByIdentifierID", ctx, identifierID)}
}

func (_c *MockICartRepository_GetByIdentifierID_Call) Run(run func(ctx context.Context, identifierID uuid.UUID)) *MockICartRepository_GetByIdentifierID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockICartRepository_GetByIdentifierID_Call) Return(cart *model.Cart, err error) *MockICartRepository_GetByIdentifierID_Call {
	_c.Call.Return(cart, err)
	return _c
}

func (_c *MockICartRepository_GetByIdentifierID_Call) RunAndReturn(run func(ctx context.Context, identifierID uuid.UUID) (*model.Cart, error)) *MockICartRepository_GetByIdentifierID_Call {
	_c.Call.Return(run)
	return _c
}

// Insert provides a mock function for the type MockICartRepository
func (_mock *MockICartRepository) Insert(ctx context.Context, cart model.Cart) error {
	ret := _mock.Called(ctx, cart)

	if len(ret) == 0 {
		panic("no return value specified for Insert")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, model.Cart) error); ok {
		r0 = returnFunc(ctx, cart)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockICartRepository_Insert_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Insert'
type MockICartRepository_Insert_Call struct {
	*mock.Call
}

// Insert is a helper method to define mock.On call
//   - ctx context.Context
//   - cart model.Cart
func (_e *MockICartRepository_Expecter) Insert(ctx any, cart any) *MockICartRepository_Insert_Call {
	return &MockICartRepository_Insert_Call{Call: _e.mock.On("Insert", ctx, cart)}
}

func (_c *MockICartRepository_Insert_Call) Run(run func(ctx context.Context, cart model.Cart)) *MockICartRepository_Insert_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 model.Cart
		if args[1] != nil {
			arg1 = args[1].(model.Cart)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockICartRepository_Insert_Call) Return(err error) *MockICartRepository_Insert_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockICartRepository_Insert_Call) RunAndReturn(run func(ctx context.Context, cart model.Cart) error) *MockICartRepository_Insert_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function for the type MockICartRepository
func (_mock *MockICartRepository) List(ctx context.Context, pagination *model0.Pagination, identifierID uuid.UUID) ([]model.Cart, *model0.Pagination, error) {
	ret := _mock.Called(ctx, pagination, identifierID)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []model.Cart
	var r1 *model0.Pagination
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *model0.Pagination, uuid.UUID) ([]model.Cart, *model0.Pagination, error)); ok {
		return returnFunc(ctx, pagination, identifierID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *model0.Pagination, uuid.UUID) []model.Cart); ok {
		r0 = returnFunc(ctx, pagination, identifierID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Cart)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *model0.Pagination, uuid.UUID) *model0.Pagination); ok {
		r1 = returnFunc(ctx, pagination, identifierID)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*model0.Pagination)
		}
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, *model0.Pagination, uuid.UUID) error); ok {
		r2 = returnFunc(ctx, pagination, identifierID)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockICartRepository_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockICartRepository_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - pagination *model0.Pagination
//   - identifierID uuid.UUID
func (_e *MockICartRepository_Expecter) List(ctx any, pagination any, identifierID any) *MockICartRepository_List_Call {
	return &MockICartRepository_List_Call{Call: _e.mock.On("List", ctx, pagination, identifierID)}
}

func (_c *MockICartRepository_List_Call) Run(run func(ctx context.Context, pagination *model0.Pagination, identifierID uuid.UUID)) *MockICartRepository_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *model0.Pagination
		if args[1] != nil {
			arg1 = args[1].(*model0.Pagination)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockICartRepository_List_Call) Return(carts []model.Cart, pagination1 *model0.Pagination, err error) *MockICartRepository_List_Call {
	_c.Call.Return(carts, pagination1, err)
	return _c
}

func (_c *MockICartRepository_List_Call) RunAndReturn(run func(ctx context.Context, pagination *model0.Pagination, identifierID uuid.UUID) ([]model.Cart, *model0.Pagination, error)) *MockICartRepository_List_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type MockICartRepository
func (_mock *MockICartRepository) Update(ctx context.Context, cart model.Cart) error {
	ret := _mock.Called(ctx, cart)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, model.Cart) error); ok {
		r0 = returnFunc(ctx, cart)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockICartRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockICartRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - cart model.Cart
func (_e *MockICartRepository_Expecter) Update(ctx any, cart any) *MockICartRepository_Update_Call {
	return &MockICartRepository_Update_Call{Call: _e.mock.On("Update", ctx, cart)}
}

func (_c *MockICartRepository_Update_Call) Run(run func(ctx context.Context, cart model.Cart)) *MockICartRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 model.Cart
		if args[1] != nil {
			arg1 = args[1].(model.Cart)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockICartRepository_Update_Call) Return(err error) *MockICartRepository_Update_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockICartRepository_Update_Call) RunAndReturn(run func(ctx context.Context, cart model.Cart) error) *MockICartRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}
