// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package repository

import (
	"context"

	mock "github.com/stretchr/testify/mock"
	"github.com/wigata-intech/logres/internal/api/model"
	model0 "github.com/wigata-intech/logres/internal/shared/model"
)

// NewMockICategoryRepository creates a new instance of MockICategoryRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockICategoryRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockICategoryRepository {
	mock := &MockICategoryRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockICategoryRepository is an autogenerated mock type for the ICategoryRepository type
type MockICategoryRepository struct {
	mock.Mock
}

type MockICategoryRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockICategoryRepository) EXPECT() *MockICategoryRepository_Expecter {
	return &MockICategoryRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockICategoryRepository
func (_mock *MockICategoryRepository) Create(ctx context.Context, category *model.Category) error {
	ret := _mock.Called(ctx, category)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *model.Category) error); ok {
		r0 = returnFunc(ctx, category)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockICategoryRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockICategoryRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - category *model.Category
func (_e *MockICategoryRepository_Expecter) Create(ctx any, category any) *MockICategoryRepository_Create_Call {
	return &MockICategoryRepository_Create_Call{Call: _e.mock.On("Create", ctx, category)}
}

func (_c *MockICategoryRepository_Create_Call) Run(run func(ctx context.Context, category *model.Category)) *MockICategoryRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *model.Category
		if args[1] != nil {
			arg1 = args[1].(*model.Category)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockICategoryRepository_Create_Call) Return(err error) *MockICategoryRepository_Create_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockICategoryRepository_Create_Call) RunAndReturn(run func(ctx context.Context, category *model.Category) error) *MockICategoryRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type MockICategoryRepository
func (_mock *MockICategoryRepository) Delete(ctx context.Context, category *model.Category) error {
	ret := _mock.Called(ctx, category)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *model.Category) error); ok {
		r0 = returnFunc(ctx, category)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockICategoryRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockICategoryRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - category *model.Category
func (_e *MockICategoryRepository_Expecter) Delete(ctx any, category any) *MockICategoryRepository_Delete_Call {
	return &MockICategoryRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, category)}
}

func (_c *MockICategoryRepository_Delete_Call) Run(run func(ctx context.Context, category *model.Category)) *MockICategoryRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *model.Category
		if args[1] != nil {
			arg1 = args[1].(*model.Category)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockICategoryRepository_Delete_Call) Return(err error) *MockICategoryRepository_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockICategoryRepository_Delete_Call) RunAndReturn(run func(ctx context.Context, category *model.Category) error) *MockICategoryRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// GetBySlug provides a mock function for the type MockICategoryRepository
func (_mock *MockICategoryRepository) GetBySlug(ctx context.Context, slug string) (*model.Category, error) {
	ret := _mock.Called(ctx, slug)

	if len(ret) == 0 {
		panic("no return value specified for GetBySlug")
	}

	var r0 *model.Category
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*model.Category, error)); ok {
		return returnFunc(ctx, slug)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *model.Category); ok {
		r0 = returnFunc(ctx, slug)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Category)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, slug)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockICategoryRepository_GetBySlug_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBySlug'
type MockICategoryRepository_GetBySlug_Call struct {
	*mock.Call
}

// GetBySlug is a helper method to define mock.On call
//   - ctx context.Context
//   - slug string
func (_e *MockICategoryRepository_Expecter) GetBySlug(ctx any, slug any) *MockICategoryRepository_GetBySlug_Call {
	return &MockICategoryRepository_GetBySlug_Call{Call: _e.mock.On("GetBySlug", ctx, slug)}
}

func (_c *MockICategoryRepository_GetBySlug_Call) Run(run func(ctx context.Context, slug string)) *MockICategoryRepository_GetBySlug_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockICategoryRepository_GetBySlug_Call) Return(category *model.Category, err error) *MockICategoryRepository_GetBySlug_Call {
	_c.Call.Return(category, err)
	return _c
}

func (_c *MockICategoryRepository_GetBySlug_Call) RunAndReturn(run func(ctx context.Context, slug string) (*model.Category, error)) *MockICategoryRepository_GetBySlug_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function for the type MockICategoryRepository
func (_mock *MockICategoryRepository) List(ctx context.Context, pagination *model0.Pagination, search string) ([]model.Category, *model0.Pagination, error) {
	ret := _mock.Called(ctx, pagination, search)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []model.Category
	var r1 *model0.Pagination
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *model0.Pagination, string) ([]model.Category, *model0.Pagination, error)); ok {
		return returnFunc(ctx, pagination, search)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *model0.Pagination, string) []model.Category); ok {
		r0 = returnFunc(ctx, pagination, search)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Category)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *model0.Pagination, string) *model0.Pagination); ok {
		r1 = returnFunc(ctx, pagination, search)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*model0.Pagination)
		}
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, *model0.Pagination, string) error); ok {
		r2 = returnFunc(ctx, pagination, search)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockICategoryRepository_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockICategoryRepository_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - pagination *model0.Pagination
//   - search string
func (_e *MockICategoryRepository_Expecter) List(ctx any, pagination any, search any) *MockICategoryRepository_List_Call {
	return &MockICategoryRepository_List_Call{Call: _e.mock.On("List", ctx, pagination, search)}
}

func (_c *MockICategoryRepository_List_Call) Run(run func(ctx context.Context, pagination *model0.Pagination, search string)) *MockICategoryRepository_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *model0.Pagination
		if args[1] != nil {
			arg1 = args[1].(*model0.Pagination)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockICategoryRepository_List_Call) Return(categorys []model.Category, pagination1 *model0.Pagination, err error) *MockICategoryRepository_List_Call {
	_c.Call.Return(categorys, pagination1, err)
	return _c
}

func (_c *MockICategoryRepository_List_Call) RunAndReturn(run func(ctx context.Context, pagination *model0.Pagination, search string) ([]model.Category, *model0.Pagination, error)) *MockICategoryRepository_List_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type MockICategoryRepository
func (_mock *MockICategoryRepository) Update(ctx context.Context, category *model.Category) error {
	ret := _mock.Called(ctx, category)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *model.Category) error); ok {
		r0 = returnFunc(ctx, category)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockICategoryRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockICategoryRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - category *model.Category
func (_e *MockICategoryRepository_Expecter) Update(ctx any, category any) *MockICategoryRepository_Update_Call {
	return &MockICategoryRepository_Update_Call{Call: _e.mock.On("Update", ctx, category)}
}

func (_c *MockICategoryRepository_Update_Call) Run(run func(ctx context.Context, category *model.Category)) *MockICategoryRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *model.Category
		if args[1] != nil {
			arg1 = args[1].(*model.Category)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockICategoryRepository_Update_Call) Return(err error) *MockICategoryRepository_Update_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockICategoryRepository_Update_Call) RunAndReturn(run func(ctx context.Context, category *model.Category) error) *MockICategoryRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}
