// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package repository

import (
	"context"

	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
	"github.com/wigata-intech/logres/internal/api/model"
	model0 "github.com/wigata-intech/logres/internal/shared/model"
)

// NewMockIFileRepository creates a new instance of MockIFileRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIFileRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIFileRepository {
	mock := &MockIFileRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockIFileRepository is an autogenerated mock type for the IFileRepository type
type MockIFileRepository struct {
	mock.Mock
}

type MockIFileRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIFileRepository) EXPECT() *MockIFileRepository_Expecter {
	return &MockIFileRepository_Expecter{mock: &_m.Mock}
}

// Delete provides a mock function for the type MockIFileRepository
func (_mock *MockIFileRepository) Delete(ctx context.Context, file *model.File) error {
	ret := _mock.Called(ctx, file)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *model.File) error); ok {
		r0 = returnFunc(ctx, file)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIFileRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockIFileRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - file *model.File
func (_e *MockIFileRepository_Expecter) Delete(ctx any, file any) *MockIFileRepository_Delete_Call {
	return &MockIFileRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, file)}
}

func (_c *MockIFileRepository_Delete_Call) Run(run func(ctx context.Context, file *model.File)) *MockIFileRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *model.File
		if args[1] != nil {
			arg1 = args[1].(*model.File)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIFileRepository_Delete_Call) Return(err error) *MockIFileRepository_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIFileRepository_Delete_Call) RunAndReturn(run func(ctx context.Context, file *model.File) error) *MockIFileRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function for the type MockIFileRepository
func (_mock *MockIFileRepository) GetByID(ctx context.Context, id uuid.UUID) (*model.File, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *model.File
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*model.File, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) *model.File); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.File)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIFileRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockIFileRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockIFileRepository_Expecter) GetByID(ctx any, id any) *MockIFileRepository_GetByID_Call {
	return &MockIFileRepository_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *MockIFileRepository_GetByID_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockIFileRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIFileRepository_GetByID_Call) Return(file *model.File, err error) *MockIFileRepository_GetByID_Call {
	_c.Call.Return(file, err)
	return _c
}

func (_c *MockIFileRepository_GetByID_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID) (*model.File, error)) *MockIFileRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// Insert provides a mock function for the type MockIFileRepository
func (_mock *MockIFileRepository) Insert(ctx context.Context, file *model.File) error {
	ret := _mock.Called(ctx, file)

	if len(ret) == 0 {
		panic("no return value specified for Insert")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *model.File) error); ok {
		r0 = returnFunc(ctx, file)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIFileRepository_Insert_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Insert'
type MockIFileRepository_Insert_Call struct {
	*mock.Call
}

// Insert is a helper method to define mock.On call
//   - ctx context.Context
//   - file *model.File
func (_e *MockIFileRepository_Expecter) Insert(ctx any, file any) *MockIFileRepository_Insert_Call {
	return &MockIFileRepository_Insert_Call{Call: _e.mock.On("Insert", ctx, file)}
}

func (_c *MockIFileRepository_Insert_Call) Run(run func(ctx context.Context, file *model.File)) *MockIFileRepository_Insert_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *model.File
		if args[1] != nil {
			arg1 = args[1].(*model.File)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIFileRepository_Insert_Call) Return(err error) *MockIFileRepository_Insert_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIFileRepository_Insert_Call) RunAndReturn(run func(ctx context.Context, file *model.File) error) *MockIFileRepository_Insert_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function for the type MockIFileRepository
func (_mock *MockIFileRepository) List(ctx context.Context, pagination *model0.Pagination, search string) ([]model.File, *model0.Pagination, error) {
	ret := _mock.Called(ctx, pagination, search)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []model.File
	var r1 *model0.Pagination
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *model0.Pagination, string) ([]model.File, *model0.Pagination, error)); ok {
		return returnFunc(ctx, pagination, search)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *model0.Pagination, string) []model.File); ok {
		r0 = returnFunc(ctx, pagination, search)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.File)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *model0.Pagination, string) *model0.Pagination); ok {
		r1 = returnFunc(ctx, pagination, search)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*model0.Pagination)
		}
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, *model0.Pagination, string) error); ok {
		r2 = returnFunc(ctx, pagination, search)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockIFileRepository_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockIFileRepository_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - pagination *model0.Pagination
//   - search string
func (_e *MockIFileRepository_Expecter) List(ctx any, pagination any, search any) *MockIFileRepository_List_Call {
	return &MockIFileRepository_List_Call{Call: _e.mock.On("List", ctx, pagination, search)}
}

func (_c *MockIFileRepository_List_Call) Run(run func(ctx context.Context, pagination *model0.Pagination, search string)) *MockIFileRepository_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *model0.Pagination
		if args[1] != nil {
			arg1 = args[1].(*model0.Pagination)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockIFileRepository_List_Call) Return(files []model.File, pagination1 *model0.Pagination, err error) *MockIFileRepository_List_Call {
	_c.Call.Return(files, pagination1, err)
	return _c
}

func (_c *MockIFileRepository_List_Call) RunAndReturn(run func(ctx context.Context, pagination *model0.Pagination, search string) ([]model.File, *model0.Pagination, error)) *MockIFileRepository_List_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type MockIFileRepository
func (_mock *MockIFileRepository) Update(ctx context.Context, file *model.File) error {
	ret := _mock.Called(ctx, file)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *model.File) error); ok {
		r0 = returnFunc(ctx, file)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIFileRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockIFileRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - file *model.File
func (_e *MockIFileRepository_Expecter) Update(ctx any, file any) *MockIFileRepository_Update_Call {
	return &MockIFileRepository_Update_Call{Call: _e.mock.On("Update", ctx, file)}
}

func (_c *MockIFileRepository_Update_Call) Run(run func(ctx context.Context, file *model.File)) *MockIFileRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *model.File
		if args[1] != nil {
			arg1 = args[1].(*model.File)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIFileRepository_Update_Call) Return(err error) *MockIFileRepository_Update_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIFileRepository_Update_Call) RunAndReturn(run func(ctx context.Context, file *model.File) error) *MockIFileRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}
