// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package repository

import (
	"context"

	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
	"github.com/wigata-intech/logres/internal/api/model"
	model0 "github.com/wigata-intech/logres/internal/shared/model"
)

// NewMockIOrderRepository creates a new instance of MockIOrderRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIOrderRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIOrderRepository {
	mock := &MockIOrderRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockIOrderRepository is an autogenerated mock type for the IOrderRepository type
type MockIOrderRepository struct {
	mock.Mock
}

type MockIOrderRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIOrderRepository) EXPECT() *MockIOrderRepository_Expecter {
	return &MockIOrderRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockIOrderRepository
func (_mock *MockIOrderRepository) Create(ctx context.Context, order *model.Order) error {
	ret := _mock.Called(ctx, order)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *model.Order) error); ok {
		r0 = returnFunc(ctx, order)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIOrderRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockIOrderRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - order *model.Order
func (_e *MockIOrderRepository_Expecter) Create(ctx any, order any) *MockIOrderRepository_Create_Call {
	return &MockIOrderRepository_Create_Call{Call: _e.mock.On("Create", ctx, order)}
}

func (_c *MockIOrderRepository_Create_Call) Run(run func(ctx context.Context, order *model.Order)) *MockIOrderRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *model.Order
		if args[1] != nil {
			arg1 = args[1].(*model.Order)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIOrderRepository_Create_Call) Return(err error) *MockIOrderRepository_Create_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIOrderRepository_Create_Call) RunAndReturn(run func(ctx context.Context, order *model.Order) error) *MockIOrderRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type MockIOrderRepository
func (_mock *MockIOrderRepository) Delete(ctx context.Context, order *model.Order) error {
	ret := _mock.Called(ctx, order)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *model.Order) error); ok {
		r0 = returnFunc(ctx, order)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIOrderRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockIOrderRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - order *model.Order
func (_e *MockIOrderRepository_Expecter) Delete(ctx any, order any) *MockIOrderRepository_Delete_Call {
	return &MockIOrderRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, order)}
}

func (_c *MockIOrderRepository_Delete_Call) Run(run func(ctx context.Context, order *model.Order)) *MockIOrderRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *model.Order
		if args[1] != nil {
			arg1 = args[1].(*model.Order)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIOrderRepository_Delete_Call) Return(err error) *MockIOrderRepository_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIOrderRepository_Delete_Call) RunAndReturn(run func(ctx context.Context, order *model.Order) error) *MockIOrderRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function for the type MockIOrderRepository
func (_mock *MockIOrderRepository) GetByID(ctx context.Context, id uuid.UUID) (*model.Order, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *model.Order
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*model.Order, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) *model.Order); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Order)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIOrderRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockIOrderRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockIOrderRepository_Expecter) GetByID(ctx any, id any) *MockIOrderRepository_GetByID_Call {
	return &MockIOrderRepository_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *MockIOrderRepository_GetByID_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockIOrderRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIOrderRepository_GetByID_Call) Return(order *model.Order, err error) *MockIOrderRepository_GetByID_Call {
	_c.Call.Return(order, err)
	return _c
}

func (_c *MockIOrderRepository_GetByID_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID) (*model.Order, error)) *MockIOrderRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function for the type MockIOrderRepository
func (_mock *MockIOrderRepository) List(ctx context.Context, pagination *model0.Pagination, search string) ([]model.Order, *model0.Pagination, error) {
	ret := _mock.Called(ctx, pagination, search)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []model.Order
	var r1 *model0.Pagination
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *model0.Pagination, string) ([]model.Order, *model0.Pagination, error)); ok {
		return returnFunc(ctx, pagination, search)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *model0.Pagination, string) []model.Order); ok {
		r0 = returnFunc(ctx, pagination, search)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Order)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *model0.Pagination, string) *model0.Pagination); ok {
		r1 = returnFunc(ctx, pagination, search)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*model0.Pagination)
		}
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, *model0.Pagination, string) error); ok {
		r2 = returnFunc(ctx, pagination, search)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockIOrderRepository_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockIOrderRepository_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - pagination *model0.Pagination
//   - search string
func (_e *MockIOrderRepository_Expecter) List(ctx any, pagination any, search any) *MockIOrderRepository_List_Call {
	return &MockIOrderRepository_List_Call{Call: _e.mock.On("List", ctx, pagination, search)}
}

func (_c *MockIOrderRepository_List_Call) Run(run func(ctx context.Context, pagination *model0.Pagination, search string)) *MockIOrderRepository_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *model0.Pagination
		if args[1] != nil {
			arg1 = args[1].(*model0.Pagination)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockIOrderRepository_List_Call) Return(orders []model.Order, pagination1 *model0.Pagination, err error) *MockIOrderRepository_List_Call {
	_c.Call.Return(orders, pagination1, err)
	return _c
}

func (_c *MockIOrderRepository_List_Call) RunAndReturn(run func(ctx context.Context, pagination *model0.Pagination, search string) ([]model.Order, *model0.Pagination, error)) *MockIOrderRepository_List_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type MockIOrderRepository
func (_mock *MockIOrderRepository) Update(ctx context.Context, order *model.Order) error {
	ret := _mock.Called(ctx, order)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *model.Order) error); ok {
		r0 = returnFunc(ctx, order)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIOrderRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockIOrderRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - order *model.Order
func (_e *MockIOrderRepository_Expecter) Update(ctx any, order any) *MockIOrderRepository_Update_Call {
	return &MockIOrderRepository_Update_Call{Call: _e.mock.On("Update", ctx, order)}
}

func (_c *MockIOrderRepository_Update_Call) Run(run func(ctx context.Context, order *model.Order)) *MockIOrderRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *model.Order
		if args[1] != nil {
			arg1 = args[1].(*model.Order)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIOrderRepository_Update_Call) Return(err error) *MockIOrderRepository_Update_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIOrderRepository_Update_Call) RunAndReturn(run func(ctx context.Context, order *model.Order) error) *MockIOrderRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}
