// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package repository

import (
	"context"

	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
	"github.com/wigata-intech/logres/internal/api/model"
	model0 "github.com/wigata-intech/logres/internal/shared/model"
)

// NewMockIProductRepository creates a new instance of MockIProductRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIProductRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIProductRepository {
	mock := &MockIProductRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockIProductRepository is an autogenerated mock type for the IProductRepository type
type MockIProductRepository struct {
	mock.Mock
}

type MockIProductRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIProductRepository) EXPECT() *MockIProductRepository_Expecter {
	return &MockIProductRepository_Expecter{mock: &_m.Mock}
}

// CategoryAssign provides a mock function for the type MockIProductRepository
func (_mock *MockIProductRepository) CategoryAssign(ctx context.Context, productCategory *model.ProductCategory) error {
	ret := _mock.Called(ctx, productCategory)

	if len(ret) == 0 {
		panic("no return value specified for CategoryAssign")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *model.ProductCategory) error); ok {
		r0 = returnFunc(ctx, productCategory)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIProductRepository_CategoryAssign_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CategoryAssign'
type MockIProductRepository_CategoryAssign_Call struct {
	*mock.Call
}

// CategoryAssign is a helper method to define mock.On call
//   - ctx context.Context
//   - productCategory *model.ProductCategory
func (_e *MockIProductRepository_Expecter) CategoryAssign(ctx any, productCategory any) *MockIProductRepository_CategoryAssign_Call {
	return &MockIProductRepository_CategoryAssign_Call{Call: _e.mock.On("CategoryAssign", ctx, productCategory)}
}

func (_c *MockIProductRepository_CategoryAssign_Call) Run(run func(ctx context.Context, productCategory *model.ProductCategory)) *MockIProductRepository_CategoryAssign_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *model.ProductCategory
		if args[1] != nil {
			arg1 = args[1].(*model.ProductCategory)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIProductRepository_CategoryAssign_Call) Return(err error) *MockIProductRepository_CategoryAssign_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIProductRepository_CategoryAssign_Call) RunAndReturn(run func(ctx context.Context, productCategory *model.ProductCategory) error) *MockIProductRepository_CategoryAssign_Call {
	_c.Call.Return(run)
	return _c
}

// CategoryListByProductID provides a mock function for the type MockIProductRepository
func (_mock *MockIProductRepository) CategoryListByProductID(ctx context.Context, productID uuid.UUID) ([]model.ProductCategory, error) {
	ret := _mock.Called(ctx, productID)

	if len(ret) == 0 {
		panic("no return value specified for CategoryListByProductID")
	}

	var r0 []model.ProductCategory
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]model.ProductCategory, error)); ok {
		return returnFunc(ctx, productID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) []model.ProductCategory); ok {
		r0 = returnFunc(ctx, productID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.ProductCategory)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, productID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIProductRepository_CategoryListByProductID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CategoryListByProductID'
type MockIProductRepository_CategoryListByProductID_Call struct {
	*mock.Call
}

// CategoryListByProductID is a helper method to define mock.On call
//   - ctx context.Context
//   - productID uuid.UUID
func (_e *MockIProductRepository_Expecter) CategoryListByProductID(ctx any, productID any) *MockIProductRepository_CategoryListByProductID_Call {
	return &MockIProductRepository_CategoryListByProductID_Call{Call: _e.mock.On("CategoryListByProductID", ctx, productID)}
}

func (_c *MockIProductRepository_CategoryListByProductID_Call) Run(run func(ctx context.Context, productID uuid.UUID)) *MockIProductRepository_CategoryListByProductID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIProductRepository_CategoryListByProductID_Call) Return(productCategorys []model.ProductCategory, err error) *MockIProductRepository_CategoryListByProductID_Call {
	_c.Call.Return(productCategorys, err)
	return _c
}

func (_c *MockIProductRepository_CategoryListByProductID_Call) RunAndReturn(run func(ctx context.Context, productID uuid.UUID) ([]model.ProductCategory, error)) *MockIProductRepository_CategoryListByProductID_Call {
	_c.Call.Return(run)
	return _c
}

// CategoryUnassign provides a mock function for the type MockIProductRepository
func (_mock *MockIProductRepository) CategoryUnassign(ctx context.Context, productCategory *model.ProductCategory) error {
	ret := _mock.Called(ctx, productCategory)

	if len(ret) == 0 {
		panic("no return value specified for CategoryUnassign")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *model.ProductCategory) error); ok {
		r0 = returnFunc(ctx, productCategory)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIProductRepository_CategoryUnassign_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CategoryUnassign'
type MockIProductRepository_CategoryUnassign_Call struct {
	*mock.Call
}

// CategoryUnassign is a helper method to define mock.On call
//   - ctx context.Context
//   - productCategory *model.ProductCategory
func (_e *MockIProductRepository_Expecter) CategoryUnassign(ctx any, productCategory any) *MockIProductRepository_CategoryUnassign_Call {
	return &MockIProductRepository_CategoryUnassign_Call{Call: _e.mock.On("CategoryUnassign", ctx, productCategory)}
}

func (_c *MockIProductRepository_CategoryUnassign_Call) Run(run func(ctx context.Context, productCategory *model.ProductCategory)) *MockIProductRepository_CategoryUnassign_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *model.ProductCategory
		if args[1] != nil {
			arg1 = args[1].(*model.ProductCategory)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIProductRepository_CategoryUnassign_Call) Return(err error) *MockIProductRepository_CategoryUnassign_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIProductRepository_CategoryUnassign_Call) RunAndReturn(run func(ctx context.Context, productCategory *model.ProductCategory) error) *MockIProductRepository_CategoryUnassign_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function for the type MockIProductRepository
func (_mock *MockIProductRepository) Create(ctx context.Context, product *model.Product) error {
	ret := _mock.Called(ctx, product)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *model.Product) error); ok {
		r0 = returnFunc(ctx, product)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIProductRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockIProductRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - product *model.Product
func (_e *MockIProductRepository_Expecter) Create(ctx any, product any) *MockIProductRepository_Create_Call {
	return &MockIProductRepository_Create_Call{Call: _e.mock.On("Create", ctx, product)}
}

func (_c *MockIProductRepository_Create_Call) Run(run func(ctx context.Context, product *model.Product)) *MockIProductRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *model.Product
		if args[1] != nil {
			arg1 = args[1].(*model.Product)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIProductRepository_Create_Call) Return(err error) *MockIProductRepository_Create_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIProductRepository_Create_Call) RunAndReturn(run func(ctx context.Context, product *model.Product) error) *MockIProductRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type MockIProductRepository
func (_mock *MockIProductRepository) Delete(ctx context.Context, product *model.Product) error {
	ret := _mock.Called(ctx, product)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *model.Product) error); ok {
		r0 = returnFunc(ctx, product)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIProductRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockIProductRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - product *model.Product
func (_e *MockIProductRepository_Expecter) Delete(ctx any, product any) *MockIProductRepository_Delete_Call {
	return &MockIProductRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, product)}
}

func (_c *MockIProductRepository_Delete_Call) Run(run func(ctx context.Context, product *model.Product)) *MockIProductRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *model.Product
		if args[1] != nil {
			arg1 = args[1].(*model.Product)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIProductRepository_Delete_Call) Return(err error) *MockIProductRepository_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIProductRepository_Delete_Call) RunAndReturn(run func(ctx context.Context, product *model.Product) error) *MockIProductRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// FileAssign provides a mock function for the type MockIProductRepository
func (_mock *MockIProductRepository) FileAssign(ctx context.Context, productFile *model.ProductFile) error {
	ret := _mock.Called(ctx, productFile)

	if len(ret) == 0 {
		panic("no return value specified for FileAssign")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *model.ProductFile) error); ok {
		r0 = returnFunc(ctx, productFile)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIProductRepository_FileAssign_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FileAssign'
type MockIProductRepository_FileAssign_Call struct {
	*mock.Call
}

// FileAssign is a helper method to define mock.On call
//   - ctx context.Context
//   - productFile *model.ProductFile
func (_e *MockIProductRepository_Expecter) FileAssign(ctx any, productFile any) *MockIProductRepository_FileAssign_Call {
	return &MockIProductRepository_FileAssign_Call{Call: _e.mock.On("FileAssign", ctx, productFile)}
}

func (_c *MockIProductRepository_FileAssign_Call) Run(run func(ctx context.Context, productFile *model.ProductFile)) *MockIProductRepository_FileAssign_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *model.ProductFile
		if args[1] != nil {
			arg1 = args[1].(*model.ProductFile)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIProductRepository_FileAssign_Call) Return(err error) *MockIProductRepository_FileAssign_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIProductRepository_FileAssign_Call) RunAndReturn(run func(ctx context.Context, productFile *model.ProductFile) error) *MockIProductRepository_FileAssign_Call {
	_c.Call.Return(run)
	return _c
}

// FileListByProductID provides a mock function for the type MockIProductRepository
func (_mock *MockIProductRepository) FileListByProductID(ctx context.Context, productID uuid.UUID) ([]model.ProductFile, error) {
	ret := _mock.Called(ctx, productID)

	if len(ret) == 0 {
		panic("no return value specified for FileListByProductID")
	}

	var r0 []model.ProductFile
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]model.ProductFile, error)); ok {
		return returnFunc(ctx, productID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) []model.ProductFile); ok {
		r0 = returnFunc(ctx, productID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.ProductFile)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, productID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIProductRepository_FileListByProductID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FileListByProductID'
type MockIProductRepository_FileListByProductID_Call struct {
	*mock.Call
}

// FileListByProductID is a helper method to define mock.On call
//   - ctx context.Context
//   - productID uuid.UUID
func (_e *MockIProductRepository_Expecter) FileListByProductID(ctx any, productID any) *MockIProductRepository_FileListByProductID_Call {
	return &MockIProductRepository_FileListByProductID_Call{Call: _e.mock.On("FileListByProductID", ctx, productID)}
}

func (_c *MockIProductRepository_FileListByProductID_Call) Run(run func(ctx context.Context, productID uuid.UUID)) *MockIProductRepository_FileListByProductID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIProductRepository_FileListByProductID_Call) Return(productFiles []model.ProductFile, err error) *MockIProductRepository_FileListByProductID_Call {
	_c.Call.Return(productFiles, err)
	return _c
}

func (_c *MockIProductRepository_FileListByProductID_Call) RunAndReturn(run func(ctx context.Context, productID uuid.UUID) ([]model.ProductFile, error)) *MockIProductRepository_FileListByProductID_Call {
	_c.Call.Return(run)
	return _c
}

// FileUnassign provides a mock function for the type MockIProductRepository
func (_mock *MockIProductRepository) FileUnassign(ctx context.Context, productFile *model.ProductFile) error {
	ret := _mock.Called(ctx, productFile)

	if len(ret) == 0 {
		panic("no return value specified for FileUnassign")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *model.ProductFile) error); ok {
		r0 = returnFunc(ctx, productFile)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIProductRepository_FileUnassign_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FileUnassign'
type MockIProductRepository_FileUnassign_Call struct {
	*mock.Call
}

// FileUnassign is a helper method to define mock.On call
//   - ctx context.Context
//   - productFile *model.ProductFile
func (_e *MockIProductRepository_Expecter) FileUnassign(ctx any, productFile any) *MockIProductRepository_FileUnassign_Call {
	return &MockIProductRepository_FileUnassign_Call{Call: _e.mock.On("FileUnassign", ctx, productFile)}
}

func (_c *MockIProductRepository_FileUnassign_Call) Run(run func(ctx context.Context, productFile *model.ProductFile)) *MockIProductRepository_FileUnassign_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *model.ProductFile
		if args[1] != nil {
			arg1 = args[1].(*model.ProductFile)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIProductRepository_FileUnassign_Call) Return(err error) *MockIProductRepository_FileUnassign_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIProductRepository_FileUnassign_Call) RunAndReturn(run func(ctx context.Context, productFile *model.ProductFile) error) *MockIProductRepository_FileUnassign_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function for the type MockIProductRepository
func (_mock *MockIProductRepository) GetByID(ctx context.Context, id uuid.UUID) (*model.Product, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *model.Product
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*model.Product, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) *model.Product); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Product)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIProductRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockIProductRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockIProductRepository_Expecter) GetByID(ctx any, id any) *MockIProductRepository_GetByID_Call {
	return &MockIProductRepository_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *MockIProductRepository_GetByID_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockIProductRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIProductRepository_GetByID_Call) Return(product *model.Product, err error) *MockIProductRepository_GetByID_Call {
	_c.Call.Return(product, err)
	return _c
}

func (_c *MockIProductRepository_GetByID_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID) (*model.Product, error)) *MockIProductRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetBySlug provides a mock function for the type MockIProductRepository
func (_mock *MockIProductRepository) GetBySlug(ctx context.Context, slug string) (*model.Product, error) {
	ret := _mock.Called(ctx, slug)

	if len(ret) == 0 {
		panic("no return value specified for GetBySlug")
	}

	var r0 *model.Product
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*model.Product, error)); ok {
		return returnFunc(ctx, slug)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *model.Product); ok {
		r0 = returnFunc(ctx, slug)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Product)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, slug)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIProductRepository_GetBySlug_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBySlug'
type MockIProductRepository_GetBySlug_Call struct {
	*mock.Call
}

// GetBySlug is a helper method to define mock.On call
//   - ctx context.Context
//   - slug string
func (_e *MockIProductRepository_Expecter) GetBySlug(ctx any, slug any) *MockIProductRepository_GetBySlug_Call {
	return &MockIProductRepository_GetBySlug_Call{Call: _e.mock.On("GetBySlug", ctx, slug)}
}

func (_c *MockIProductRepository_GetBySlug_Call) Run(run func(ctx context.Context, slug string)) *MockIProductRepository_GetBySlug_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIProductRepository_GetBySlug_Call) Return(product *model.Product, err error) *MockIProductRepository_GetBySlug_Call {
	_c.Call.Return(product, err)
	return _c
}

func (_c *MockIProductRepository_GetBySlug_Call) RunAndReturn(run func(ctx context.Context, slug string) (*model.Product, error)) *MockIProductRepository_GetBySlug_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function for the type MockIProductRepository
func (_mock *MockIProductRepository) List(ctx context.Context, pagination *model0.Pagination, search string) ([]model.Product, *model0.Pagination, error) {
	ret := _mock.Called(ctx, pagination, search)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []model.Product
	var r1 *model0.Pagination
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *model0.Pagination, string) ([]model.Product, *model0.Pagination, error)); ok {
		return returnFunc(ctx, pagination, search)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *model0.Pagination, string) []model.Product); ok {
		r0 = returnFunc(ctx, pagination, search)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Product)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *model0.Pagination, string) *model0.Pagination); ok {
		r1 = returnFunc(ctx, pagination, search)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*model0.Pagination)
		}
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, *model0.Pagination, string) error); ok {
		r2 = returnFunc(ctx, pagination, search)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockIProductRepository_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockIProductRepository_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - pagination *model0.Pagination
//   - search string
func (_e *MockIProductRepository_Expecter) List(ctx any, pagination any, search any) *MockIProductRepository_List_Call {
	return &MockIProductRepository_List_Call{Call: _e.mock.On("List", ctx, pagination, search)}
}

func (_c *MockIProductRepository_List_Call) Run(run func(ctx context.Context, pagination *model0.Pagination, search string)) *MockIProductRepository_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *model0.Pagination
		if args[1] != nil {
			arg1 = args[1].(*model0.Pagination)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockIProductRepository_List_Call) Return(products []model.Product, pagination1 *model0.Pagination, err error) *MockIProductRepository_List_Call {
	_c.Call.Return(products, pagination1, err)
	return _c
}

func (_c *MockIProductRepository_List_Call) RunAndReturn(run func(ctx context.Context, pagination *model0.Pagination, search string) ([]model.Product, *model0.Pagination, error)) *MockIProductRepository_List_Call {
	_c.Call.Return(run)
	return _c
}

// TagAssign provides a mock function for the type MockIProductRepository
func (_mock *MockIProductRepository) TagAssign(ctx context.Context, productTag *model.ProductTag) error {
	ret := _mock.Called(ctx, productTag)

	if len(ret) == 0 {
		panic("no return value specified for TagAssign")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *model.ProductTag) error); ok {
		r0 = returnFunc(ctx, productTag)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIProductRepository_TagAssign_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'TagAssign'
type MockIProductRepository_TagAssign_Call struct {
	*mock.Call
}

// TagAssign is a helper method to define mock.On call
//   - ctx context.Context
//   - productTag *model.ProductTag
func (_e *MockIProductRepository_Expecter) TagAssign(ctx any, productTag any) *MockIProductRepository_TagAssign_Call {
	return &MockIProductRepository_TagAssign_Call{Call: _e.mock.On("TagAssign", ctx, productTag)}
}

func (_c *MockIProductRepository_TagAssign_Call) Run(run func(ctx context.Context, productTag *model.ProductTag)) *MockIProductRepository_TagAssign_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *model.ProductTag
		if args[1] != nil {
			arg1 = args[1].(*model.ProductTag)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIProductRepository_TagAssign_Call) Return(err error) *MockIProductRepository_TagAssign_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIProductRepository_TagAssign_Call) RunAndReturn(run func(ctx context.Context, productTag *model.ProductTag) error) *MockIProductRepository_TagAssign_Call {
	_c.Call.Return(run)
	return _c
}

// TagListByProductID provides a mock function for the type MockIProductRepository
func (_mock *MockIProductRepository) TagListByProductID(ctx context.Context, productID uuid.UUID) ([]model.ProductTag, error) {
	ret := _mock.Called(ctx, productID)

	if len(ret) == 0 {
		panic("no return value specified for TagListByProductID")
	}

	var r0 []model.ProductTag
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]model.ProductTag, error)); ok {
		return returnFunc(ctx, productID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) []model.ProductTag); ok {
		r0 = returnFunc(ctx, productID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.ProductTag)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, productID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIProductRepository_TagListByProductID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'TagListByProductID'
type MockIProductRepository_TagListByProductID_Call struct {
	*mock.Call
}

// TagListByProductID is a helper method to define mock.On call
//   - ctx context.Context
//   - productID uuid.UUID
func (_e *MockIProductRepository_Expecter) TagListByProductID(ctx any, productID any) *MockIProductRepository_TagListByProductID_Call {
	return &MockIProductRepository_TagListByProductID_Call{Call: _e.mock.On("TagListByProductID", ctx, productID)}
}

func (_c *MockIProductRepository_TagListByProductID_Call) Run(run func(ctx context.Context, productID uuid.UUID)) *MockIProductRepository_TagListByProductID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIProductRepository_TagListByProductID_Call) Return(productTags []model.ProductTag, err error) *MockIProductRepository_TagListByProductID_Call {
	_c.Call.Return(productTags, err)
	return _c
}

func (_c *MockIProductRepository_TagListByProductID_Call) RunAndReturn(run func(ctx context.Context, productID uuid.UUID) ([]model.ProductTag, error)) *MockIProductRepository_TagListByProductID_Call {
	_c.Call.Return(run)
	return _c
}

// TagUnassign provides a mock function for the type MockIProductRepository
func (_mock *MockIProductRepository) TagUnassign(ctx context.Context, productTag *model.ProductTag) error {
	ret := _mock.Called(ctx, productTag)

	if len(ret) == 0 {
		panic("no return value specified for TagUnassign")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *model.ProductTag) error); ok {
		r0 = returnFunc(ctx, productTag)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIProductRepository_TagUnassign_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'TagUnassign'
type MockIProductRepository_TagUnassign_Call struct {
	*mock.Call
}

// TagUnassign is a helper method to define mock.On call
//   - ctx context.Context
//   - productTag *model.ProductTag
func (_e *MockIProductRepository_Expecter) TagUnassign(ctx any, productTag any) *MockIProductRepository_TagUnassign_Call {
	return &MockIProductRepository_TagUnassign_Call{Call: _e.mock.On("TagUnassign", ctx, productTag)}
}

func (_c *MockIProductRepository_TagUnassign_Call) Run(run func(ctx context.Context, productTag *model.ProductTag)) *MockIProductRepository_TagUnassign_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *model.ProductTag
		if args[1] != nil {
			arg1 = args[1].(*model.ProductTag)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIProductRepository_TagUnassign_Call) Return(err error) *MockIProductRepository_TagUnassign_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIProductRepository_TagUnassign_Call) RunAndReturn(run func(ctx context.Context, productTag *model.ProductTag) error) *MockIProductRepository_TagUnassign_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type MockIProductRepository
func (_mock *MockIProductRepository) Update(ctx context.Context, product *model.Product) error {
	ret := _mock.Called(ctx, product)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *model.Product) error); ok {
		r0 = returnFunc(ctx, product)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIProductRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockIProductRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - product *model.Product
func (_e *MockIProductRepository_Expecter) Update(ctx any, product any) *MockIProductRepository_Update_Call {
	return &MockIProductRepository_Update_Call{Call: _e.mock.On("Update", ctx, product)}
}

func (_c *MockIProductRepository_Update_Call) Run(run func(ctx context.Context, product *model.Product)) *MockIProductRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *model.Product
		if args[1] != nil {
			arg1 = args[1].(*model.Product)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIProductRepository_Update_Call) Return(err error) *MockIProductRepository_Update_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIProductRepository_Update_Call) RunAndReturn(run func(ctx context.Context, product *model.Product) error) *MockIProductRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}
