// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package repository

import (
	"context"

	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
	"github.com/wigata-intech/logres/internal/api/model"
	model0 "github.com/wigata-intech/logres/internal/shared/model"
)

// NewMockITagRepository creates a new instance of MockITagRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockITagRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockITagRepository {
	mock := &MockITagRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockITagRepository is an autogenerated mock type for the ITagRepository type
type MockITagRepository struct {
	mock.Mock
}

type MockITagRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockITagRepository) EXPECT() *MockITagRepository_Expecter {
	return &MockITagRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockITagRepository
func (_mock *MockITagRepository) Create(ctx context.Context, tag model.Tag) error {
	ret := _mock.Called(ctx, tag)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, model.Tag) error); ok {
		r0 = returnFunc(ctx, tag)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockITagRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockITagRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - tag model.Tag
func (_e *MockITagRepository_Expecter) Create(ctx any, tag any) *MockITagRepository_Create_Call {
	return &MockITagRepository_Create_Call{Call: _e.mock.On("Create", ctx, tag)}
}

func (_c *MockITagRepository_Create_Call) Run(run func(ctx context.Context, tag model.Tag)) *MockITagRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 model.Tag
		if args[1] != nil {
			arg1 = args[1].(model.Tag)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockITagRepository_Create_Call) Return(err error) *MockITagRepository_Create_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockITagRepository_Create_Call) RunAndReturn(run func(ctx context.Context, tag model.Tag) error) *MockITagRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type MockITagRepository
func (_mock *MockITagRepository) Delete(ctx context.Context, tag model.Tag) error {
	ret := _mock.Called(ctx, tag)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, model.Tag) error); ok {
		r0 = returnFunc(ctx, tag)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockITagRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockITagRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - tag model.Tag
func (_e *MockITagRepository_Expecter) Delete(ctx any, tag any) *MockITagRepository_Delete_Call {
	return &MockITagRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, tag)}
}

func (_c *MockITagRepository_Delete_Call) Run(run func(ctx context.Context, tag model.Tag)) *MockITagRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 model.Tag
		if args[1] != nil {
			arg1 = args[1].(model.Tag)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockITagRepository_Delete_Call) Return(err error) *MockITagRepository_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockITagRepository_Delete_Call) RunAndReturn(run func(ctx context.Context, tag model.Tag) error) *MockITagRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function for the type MockITagRepository
func (_mock *MockITagRepository) GetByID(ctx context.Context, id uuid.UUID) (*model.Tag, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *model.Tag
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*model.Tag, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) *model.Tag); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Tag)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockITagRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockITagRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockITagRepository_Expecter) GetByID(ctx any, id any) *MockITagRepository_GetByID_Call {
	return &MockITagRepository_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *MockITagRepository_GetByID_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockITagRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockITagRepository_GetByID_Call) Return(tag *model.Tag, err error) *MockITagRepository_GetByID_Call {
	_c.Call.Return(tag, err)
	return _c
}

func (_c *MockITagRepository_GetByID_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID) (*model.Tag, error)) *MockITagRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function for the type MockITagRepository
func (_mock *MockITagRepository) List(ctx context.Context, pagination *model0.Pagination, search string) ([]model.Tag, *model0.Pagination, error) {
	ret := _mock.Called(ctx, pagination, search)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []model.Tag
	var r1 *model0.Pagination
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *model0.Pagination, string) ([]model.Tag, *model0.Pagination, error)); ok {
		return returnFunc(ctx, pagination, search)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *model0.Pagination, string) []model.Tag); ok {
		r0 = returnFunc(ctx, pagination, search)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Tag)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *model0.Pagination, string) *model0.Pagination); ok {
		r1 = returnFunc(ctx, pagination, search)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*model0.Pagination)
		}
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, *model0.Pagination, string) error); ok {
		r2 = returnFunc(ctx, pagination, search)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockITagRepository_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockITagRepository_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - pagination *model0.Pagination
//   - search string
func (_e *MockITagRepository_Expecter) List(ctx any, pagination any, search any) *MockITagRepository_List_Call {
	return &MockITagRepository_List_Call{Call: _e.mock.On("List", ctx, pagination, search)}
}

func (_c *MockITagRepository_List_Call) Run(run func(ctx context.Context, pagination *model0.Pagination, search string)) *MockITagRepository_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *model0.Pagination
		if args[1] != nil {
			arg1 = args[1].(*model0.Pagination)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockITagRepository_List_Call) Return(tags []model.Tag, pagination1 *model0.Pagination, err error) *MockITagRepository_List_Call {
	_c.Call.Return(tags, pagination1, err)
	return _c
}

func (_c *MockITagRepository_List_Call) RunAndReturn(run func(ctx context.Context, pagination *model0.Pagination, search string) ([]model.Tag, *model0.Pagination, error)) *MockITagRepository_List_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type MockITagRepository
func (_mock *MockITagRepository) Update(ctx context.Context, tag model.Tag) error {
	ret := _mock.Called(ctx, tag)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, model.Tag) error); ok {
		r0 = returnFunc(ctx, tag)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockITagRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockITagRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - tag model.Tag
func (_e *MockITagRepository_Expecter) Update(ctx any, tag any) *MockITagRepository_Update_Call {
	return &MockITagRepository_Update_Call{Call: _e.mock.On("Update", ctx, tag)}
}

func (_c *MockITagRepository_Update_Call) Run(run func(ctx context.Context, tag model.Tag)) *MockITagRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 model.Tag
		if args[1] != nil {
			arg1 = args[1].(model.Tag)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockITagRepository_Update_Call) Return(err error) *MockITagRepository_Update_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockITagRepository_Update_Call) RunAndReturn(run func(ctx context.Context, tag model.Tag) error) *MockITagRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}
