// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package service

import (
	"context"

	mock "github.com/stretchr/testify/mock"
	"github.com/wigata-intech/logres/internal/shared/model"
)

// NewMockIAdminFileService creates a new instance of MockIAdminFileService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIAdminFileService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIAdminFileService {
	mock := &MockIAdminFileService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockIAdminFileService is an autogenerated mock type for the IAdminFileService type
type MockIAdminFileService struct {
	mock.Mock
}

type MockIAdminFileService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIAdminFileService) EXPECT() *MockIAdminFileService_Expecter {
	return &MockIAdminFileService_Expecter{mock: &_m.Mock}
}

// Delete provides a mock function for the type MockIAdminFileService
func (_mock *MockIAdminFileService) Delete(ctx context.Context, req *model.AdminFileDeleteRequest) error {
	ret := _mock.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *model.AdminFileDeleteRequest) error); ok {
		r0 = returnFunc(ctx, req)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIAdminFileService_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockIAdminFileService_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - req *model.AdminFileDeleteRequest
func (_e *MockIAdminFileService_Expecter) Delete(ctx any, req any) *MockIAdminFileService_Delete_Call {
	return &MockIAdminFileService_Delete_Call{Call: _e.mock.On("Delete", ctx, req)}
}

func (_c *MockIAdminFileService_Delete_Call) Run(run func(ctx context.Context, req *model.AdminFileDeleteRequest)) *MockIAdminFileService_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *model.AdminFileDeleteRequest
		if args[1] != nil {
			arg1 = args[1].(*model.AdminFileDeleteRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIAdminFileService_Delete_Call) Return(err error) *MockIAdminFileService_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIAdminFileService_Delete_Call) RunAndReturn(run func(ctx context.Context, req *model.AdminFileDeleteRequest) error) *MockIAdminFileService_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Detail provides a mock function for the type MockIAdminFileService
func (_mock *MockIAdminFileService) Detail(ctx context.Context, req *model.AdminFileDetailRequest) (*model.AdminFileResponse, error) {
	ret := _mock.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for Detail")
	}

	var r0 *model.AdminFileResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *model.AdminFileDetailRequest) (*model.AdminFileResponse, error)); ok {
		return returnFunc(ctx, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *model.AdminFileDetailRequest) *model.AdminFileResponse); ok {
		r0 = returnFunc(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.AdminFileResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *model.AdminFileDetailRequest) error); ok {
		r1 = returnFunc(ctx, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIAdminFileService_Detail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Detail'
type MockIAdminFileService_Detail_Call struct {
	*mock.Call
}

// Detail is a helper method to define mock.On call
//   - ctx context.Context
//   - req *model.AdminFileDetailRequest
func (_e *MockIAdminFileService_Expecter) Detail(ctx any, req any) *MockIAdminFileService_Detail_Call {
	return &MockIAdminFileService_Detail_Call{Call: _e.mock.On("Detail", ctx, req)}
}

func (_c *MockIAdminFileService_Detail_Call) Run(run func(ctx context.Context, req *model.AdminFileDetailRequest)) *MockIAdminFileService_Detail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *model.AdminFileDetailRequest
		if args[1] != nil {
			arg1 = args[1].(*model.AdminFileDetailRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIAdminFileService_Detail_Call) Return(adminFileResponse *model.AdminFileResponse, err error) *MockIAdminFileService_Detail_Call {
	_c.Call.Return(adminFileResponse, err)
	return _c
}

func (_c *MockIAdminFileService_Detail_Call) RunAndReturn(run func(ctx context.Context, req *model.AdminFileDetailRequest) (*model.AdminFileResponse, error)) *MockIAdminFileService_Detail_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function for the type MockIAdminFileService
func (_mock *MockIAdminFileService) List(ctx context.Context, req *model.AdminFileListRequest) (*model.AdminFileListResponse, error) {
	ret := _mock.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 *model.AdminFileListResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *model.AdminFileListRequest) (*model.AdminFileListResponse, error)); ok {
		return returnFunc(ctx, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *model.AdminFileListRequest) *model.AdminFileListResponse); ok {
		r0 = returnFunc(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.AdminFileListResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *model.AdminFileListRequest) error); ok {
		r1 = returnFunc(ctx, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIAdminFileService_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockIAdminFileService_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - req *model.AdminFileListRequest
func (_e *MockIAdminFileService_Expecter) List(ctx any, req any) *MockIAdminFileService_List_Call {
	return &MockIAdminFileService_List_Call{Call: _e.mock.On("List", ctx, req)}
}

func (_c *MockIAdminFileService_List_Call) Run(run func(ctx context.Context, req *model.AdminFileListRequest)) *MockIAdminFileService_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *model.AdminFileListRequest
		if args[1] != nil {
			arg1 = args[1].(*model.AdminFileListRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIAdminFileService_List_Call) Return(adminFileListResponse *model.AdminFileListResponse, err error) *MockIAdminFileService_List_Call {
	_c.Call.Return(adminFileListResponse, err)
	return _c
}

func (_c *MockIAdminFileService_List_Call) RunAndReturn(run func(ctx context.Context, req *model.AdminFileListRequest) (*model.AdminFileListResponse, error)) *MockIAdminFileService_List_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type MockIAdminFileService
func (_mock *MockIAdminFileService) Update(ctx context.Context, req *model.AdminFileUpdateRequest) (*model.AdminFileResponse, error) {
	ret := _mock.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 *model.AdminFileResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *model.AdminFileUpdateRequest) (*model.AdminFileResponse, error)); ok {
		return returnFunc(ctx, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *model.AdminFileUpdateRequest) *model.AdminFileResponse); ok {
		r0 = returnFunc(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.AdminFileResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *model.AdminFileUpdateRequest) error); ok {
		r1 = returnFunc(ctx, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIAdminFileService_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockIAdminFileService_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - req *model.AdminFileUpdateRequest
func (_e *MockIAdminFileService_Expecter) Update(ctx any, req any) *MockIAdminFileService_Update_Call {
	return &MockIAdminFileService_Update_Call{Call: _e.mock.On("Update", ctx, req)}
}

func (_c *MockIAdminFileService_Update_Call) Run(run func(ctx context.Context, req *model.AdminFileUpdateRequest)) *MockIAdminFileService_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *model.AdminFileUpdateRequest
		if args[1] != nil {
			arg1 = args[1].(*model.AdminFileUpdateRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIAdminFileService_Update_Call) Return(adminFileResponse *model.AdminFileResponse, err error) *MockIAdminFileService_Update_Call {
	_c.Call.Return(adminFileResponse, err)
	return _c
}

func (_c *MockIAdminFileService_Update_Call) RunAndReturn(run func(ctx context.Context, req *model.AdminFileUpdateRequest) (*model.AdminFileResponse, error)) *MockIAdminFileService_Update_Call {
	_c.Call.Return(run)
	return _c
}

// Upload provides a mock function for the type MockIAdminFileService
func (_mock *MockIAdminFileService) Upload(ctx context.Context, req *model.AdminFileUploadRequest) (*model.AdminFileResponse, error) {
	ret := _mock.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for Upload")
	}

	var r0 *model.AdminFileResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *model.AdminFileUploadRequest) (*model.AdminFileResponse, error)); ok {
		return returnFunc(ctx, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *model.AdminFileUploadRequest) *model.AdminFileResponse); ok {
		r0 = returnFunc(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.AdminFileResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *model.AdminFileUploadRequest) error); ok {
		r1 = returnFunc(ctx, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIAdminFileService_Upload_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Upload'
type MockIAdminFileService_Upload_Call struct {
	*mock.Call
}

// Upload is a helper method to define mock.On call
//   - ctx context.Context
//   - req *model.AdminFileUploadRequest
func (_e *MockIAdminFileService_Expecter) Upload(ctx any, req any) *MockIAdminFileService_Upload_Call {
	return &MockIAdminFileService_Upload_Call{Call: _e.mock.On("Upload", ctx, req)}
}

func (_c *MockIAdminFileService_Upload_Call) Run(run func(ctx context.Context, req *model.AdminFileUploadRequest)) *MockIAdminFileService_Upload_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *model.AdminFileUploadRequest
		if args[1] != nil {
			arg1 = args[1].(*model.AdminFileUploadRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIAdminFileService_Upload_Call) Return(adminFileResponse *model.AdminFileResponse, err error) *MockIAdminFileService_Upload_Call {
	_c.Call.Return(adminFileResponse, err)
	return _c
}

func (_c *MockIAdminFileService_Upload_Call) RunAndReturn(run func(ctx context.Context, req *model.AdminFileUploadRequest) (*model.AdminFileResponse, error)) *MockIAdminFileService_Upload_Call {
	_c.Call.Return(run)
	return _c
}
