// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package service

import (
	"context"

	mock "github.com/stretchr/testify/mock"
	"github.com/wigata-intech/logres/internal/shared/model"
)

// NewMockIAdminUserService creates a new instance of MockIAdminUserService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIAdminUserService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIAdminUserService {
	mock := &MockIAdminUserService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockIAdminUserService is an autogenerated mock type for the IAdminUserService type
type MockIAdminUserService struct {
	mock.Mock
}

type MockIAdminUserService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIAdminUserService) EXPECT() *MockIAdminUserService_Expecter {
	return &MockIAdminUserService_Expecter{mock: &_m.Mock}
}

// ChangePassword provides a mock function for the type MockIAdminUserService
func (_mock *MockIAdminUserService) ChangePassword(ctx context.Context, req *model.AdminChangePasswordRequest) (*model.AdminChangePasswordResponse, error) {
	ret := _mock.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for ChangePassword")
	}

	var r0 *model.AdminChangePasswordResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *model.AdminChangePasswordRequest) (*model.AdminChangePasswordResponse, error)); ok {
		return returnFunc(ctx, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *model.AdminChangePasswordRequest) *model.AdminChangePasswordResponse); ok {
		r0 = returnFunc(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.AdminChangePasswordResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *model.AdminChangePasswordRequest) error); ok {
		r1 = returnFunc(ctx, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIAdminUserService_ChangePassword_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ChangePassword'
type MockIAdminUserService_ChangePassword_Call struct {
	*mock.Call
}

// ChangePassword is a helper method to define mock.On call
//   - ctx context.Context
//   - req *model.AdminChangePasswordRequest
func (_e *MockIAdminUserService_Expecter) ChangePassword(ctx any, req any) *MockIAdminUserService_ChangePassword_Call {
	return &MockIAdminUserService_ChangePassword_Call{Call: _e.mock.On("ChangePassword", ctx, req)}
}

func (_c *MockIAdminUserService_ChangePassword_Call) Run(run func(ctx context.Context, req *model.AdminChangePasswordRequest)) *MockIAdminUserService_ChangePassword_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *model.AdminChangePasswordRequest
		if args[1] != nil {
			arg1 = args[1].(*model.AdminChangePasswordRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIAdminUserService_ChangePassword_Call) Return(adminChangePasswordResponse *model.AdminChangePasswordResponse, err error) *MockIAdminUserService_ChangePassword_Call {
	_c.Call.Return(adminChangePasswordResponse, err)
	return _c
}

func (_c *MockIAdminUserService_ChangePassword_Call) RunAndReturn(run func(ctx context.Context, req *model.AdminChangePasswordRequest) (*model.AdminChangePasswordResponse, error)) *MockIAdminUserService_ChangePassword_Call {
	_c.Call.Return(run)
	return _c
}

// ForgotPassword provides a mock function for the type MockIAdminUserService
func (_mock *MockIAdminUserService) ForgotPassword(ctx context.Context, req *model.AdminForgotPasswordRequest) (*model.AdminForgotPasswordResponse, error) {
	ret := _mock.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for ForgotPassword")
	}

	var r0 *model.AdminForgotPasswordResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *model.AdminForgotPasswordRequest) (*model.AdminForgotPasswordResponse, error)); ok {
		return returnFunc(ctx, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *model.AdminForgotPasswordRequest) *model.AdminForgotPasswordResponse); ok {
		r0 = returnFunc(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.AdminForgotPasswordResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *model.AdminForgotPasswordRequest) error); ok {
		r1 = returnFunc(ctx, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIAdminUserService_ForgotPassword_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ForgotPassword'
type MockIAdminUserService_ForgotPassword_Call struct {
	*mock.Call
}

// ForgotPassword is a helper method to define mock.On call
//   - ctx context.Context
//   - req *model.AdminForgotPasswordRequest
func (_e *MockIAdminUserService_Expecter) ForgotPassword(ctx any, req any) *MockIAdminUserService_ForgotPassword_Call {
	return &MockIAdminUserService_ForgotPassword_Call{Call: _e.mock.On("ForgotPassword", ctx, req)}
}

func (_c *MockIAdminUserService_ForgotPassword_Call) Run(run func(ctx context.Context, req *model.AdminForgotPasswordRequest)) *MockIAdminUserService_ForgotPassword_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *model.AdminForgotPasswordRequest
		if args[1] != nil {
			arg1 = args[1].(*model.AdminForgotPasswordRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIAdminUserService_ForgotPassword_Call) Return(adminForgotPasswordResponse *model.AdminForgotPasswordResponse, err error) *MockIAdminUserService_ForgotPassword_Call {
	_c.Call.Return(adminForgotPasswordResponse, err)
	return _c
}

func (_c *MockIAdminUserService_ForgotPassword_Call) RunAndReturn(run func(ctx context.Context, req *model.AdminForgotPasswordRequest) (*model.AdminForgotPasswordResponse, error)) *MockIAdminUserService_ForgotPassword_Call {
	_c.Call.Return(run)
	return _c
}

// Login provides a mock function for the type MockIAdminUserService
func (_mock *MockIAdminUserService) Login(ctx context.Context, req *model.AdminLoginRequest) (*model.AdminTokenResponse, error) {
	ret := _mock.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for Login")
	}

	var r0 *model.AdminTokenResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *model.AdminLoginRequest) (*model.AdminTokenResponse, error)); ok {
		return returnFunc(ctx, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *model.AdminLoginRequest) *model.AdminTokenResponse); ok {
		r0 = returnFunc(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.AdminTokenResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *model.AdminLoginRequest) error); ok {
		r1 = returnFunc(ctx, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIAdminUserService_Login_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Login'
type MockIAdminUserService_Login_Call struct {
	*mock.Call
}

// Login is a helper method to define mock.On call
//   - ctx context.Context
//   - req *model.AdminLoginRequest
func (_e *MockIAdminUserService_Expecter) Login(ctx any, req any) *MockIAdminUserService_Login_Call {
	return &MockIAdminUserService_Login_Call{Call: _e.mock.On("Login", ctx, req)}
}

func (_c *MockIAdminUserService_Login_Call) Run(run func(ctx context.Context, req *model.AdminLoginRequest)) *MockIAdminUserService_Login_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *model.AdminLoginRequest
		if args[1] != nil {
			arg1 = args[1].(*model.AdminLoginRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIAdminUserService_Login_Call) Return(adminTokenResponse *model.AdminTokenResponse, err error) *MockIAdminUserService_Login_Call {
	_c.Call.Return(adminTokenResponse, err)
	return _c
}

func (_c *MockIAdminUserService_Login_Call) RunAndReturn(run func(ctx context.Context, req *model.AdminLoginRequest) (*model.AdminTokenResponse, error)) *MockIAdminUserService_Login_Call {
	_c.Call.Return(run)
	return _c
}

// RefreshToken provides a mock function for the type MockIAdminUserService
func (_mock *MockIAdminUserService) RefreshToken(ctx context.Context, req *model.AdminRefreshTokenRequest) (*model.AdminTokenResponse, error) {
	ret := _mock.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for RefreshToken")
	}

	var r0 *model.AdminTokenResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *model.AdminRefreshTokenRequest) (*model.AdminTokenResponse, error)); ok {
		return returnFunc(ctx, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *model.AdminRefreshTokenRequest) *model.AdminTokenResponse); ok {
		r0 = returnFunc(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.AdminTokenResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *model.AdminRefreshTokenRequest) error); ok {
		r1 = returnFunc(ctx, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIAdminUserService_RefreshToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RefreshToken'
type MockIAdminUserService_RefreshToken_Call struct {
	*mock.Call
}

// RefreshToken is a helper method to define mock.On call
//   - ctx context.Context
//   - req *model.AdminRefreshTokenRequest
func (_e *MockIAdminUserService_Expecter) RefreshToken(ctx any, req any) *MockIAdminUserService_RefreshToken_Call {
	return &MockIAdminUserService_RefreshToken_Call{Call: _e.mock.On("RefreshToken", ctx, req)}
}

func (_c *MockIAdminUserService_RefreshToken_Call) Run(run func(ctx context.Context, req *model.AdminRefreshTokenRequest)) *MockIAdminUserService_RefreshToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *model.AdminRefreshTokenRequest
		if args[1] != nil {
			arg1 = args[1].(*model.AdminRefreshTokenRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIAdminUserService_RefreshToken_Call) Return(adminTokenResponse *model.AdminTokenResponse, err error) *MockIAdminUserService_RefreshToken_Call {
	_c.Call.Return(adminTokenResponse, err)
	return _c
}

func (_c *MockIAdminUserService_RefreshToken_Call) RunAndReturn(run func(ctx context.Context, req *model.AdminRefreshTokenRequest) (*model.AdminTokenResponse, error)) *MockIAdminUserService_RefreshToken_Call {
	_c.Call.Return(run)
	return _c
}

// Setup provides a mock function for the type MockIAdminUserService
func (_mock *MockIAdminUserService) Setup(ctx context.Context, req *model.AdminSetupRequest) (*model.AdminSetupResponse, error) {
	ret := _mock.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for Setup")
	}

	var r0 *model.AdminSetupResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *model.AdminSetupRequest) (*model.AdminSetupResponse, error)); ok {
		return returnFunc(ctx, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *model.AdminSetupRequest) *model.AdminSetupResponse); ok {
		r0 = returnFunc(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.AdminSetupResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *model.AdminSetupRequest) error); ok {
		r1 = returnFunc(ctx, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIAdminUserService_Setup_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Setup'
type MockIAdminUserService_Setup_Call struct {
	*mock.Call
}

// Setup is a helper method to define mock.On call
//   - ctx context.Context
//   - req *model.AdminSetupRequest
func (_e *MockIAdminUserService_Expecter) Setup(ctx any, req any) *MockIAdminUserService_Setup_Call {
	return &MockIAdminUserService_Setup_Call{Call: _e.mock.On("Setup", ctx, req)}
}

func (_c *MockIAdminUserService_Setup_Call) Run(run func(ctx context.Context, req *model.AdminSetupRequest)) *MockIAdminUserService_Setup_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *model.AdminSetupRequest
		if args[1] != nil {
			arg1 = args[1].(*model.AdminSetupRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIAdminUserService_Setup_Call) Return(adminSetupResponse *model.AdminSetupResponse, err error) *MockIAdminUserService_Setup_Call {
	_c.Call.Return(adminSetupResponse, err)
	return _c
}

func (_c *MockIAdminUserService_Setup_Call) RunAndReturn(run func(ctx context.Context, req *model.AdminSetupRequest) (*model.AdminSetupResponse, error)) *MockIAdminUserService_Setup_Call {
	_c.Call.Return(run)
	return _c
}
