// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package service

import (
	"context"

	mock "github.com/stretchr/testify/mock"
	"github.com/wigata-intech/logres/internal/shared/model"
)

// NewMockIAdminProductService creates a new instance of MockIAdminProductService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIAdminProductService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIAdminProductService {
	mock := &MockIAdminProductService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockIAdminProductService is an autogenerated mock type for the IAdminProductService type
type MockIAdminProductService struct {
	mock.Mock
}

type MockIAdminProductService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIAdminProductService) EXPECT() *MockIAdminProductService_Expecter {
	return &MockIAdminProductService_Expecter{mock: &_m.Mock}
}

// CategoryCreate provides a mock function for the type MockIAdminProductService
func (_mock *MockIAdminProductService) CategoryCreate(ctx context.Context, req *model.AdminCategoryCreateRequest) (*model.AdminCategoryResponse, error) {
	ret := _mock.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for CategoryCreate")
	}

	var r0 *model.AdminCategoryResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *model.AdminCategoryCreateRequest) (*model.AdminCategoryResponse, error)); ok {
		return returnFunc(ctx, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *model.AdminCategoryCreateRequest) *model.AdminCategoryResponse); ok {
		r0 = returnFunc(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.AdminCategoryResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *model.AdminCategoryCreateRequest) error); ok {
		r1 = returnFunc(ctx, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIAdminProductService_CategoryCreate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CategoryCreate'
type MockIAdminProductService_CategoryCreate_Call struct {
	*mock.Call
}

// CategoryCreate is a helper method to define mock.On call
//   - ctx context.Context
//   - req *model.AdminCategoryCreateRequest
func (_e *MockIAdminProductService_Expecter) CategoryCreate(ctx any, req any) *MockIAdminProductService_CategoryCreate_Call {
	return &MockIAdminProductService_CategoryCreate_Call{Call: _e.mock.On("CategoryCreate", ctx, req)}
}

func (_c *MockIAdminProductService_CategoryCreate_Call) Run(run func(ctx context.Context, req *model.AdminCategoryCreateRequest)) *MockIAdminProductService_CategoryCreate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *model.AdminCategoryCreateRequest
		if args[1] != nil {
			arg1 = args[1].(*model.AdminCategoryCreateRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIAdminProductService_CategoryCreate_Call) Return(adminCategoryResponse *model.AdminCategoryResponse, err error) *MockIAdminProductService_CategoryCreate_Call {
	_c.Call.Return(adminCategoryResponse, err)
	return _c
}

func (_c *MockIAdminProductService_CategoryCreate_Call) RunAndReturn(run func(ctx context.Context, req *model.AdminCategoryCreateRequest) (*model.AdminCategoryResponse, error)) *MockIAdminProductService_CategoryCreate_Call {
	_c.Call.Return(run)
	return _c
}

// CategoryDelete provides a mock function for the type MockIAdminProductService
func (_mock *MockIAdminProductService) CategoryDelete(ctx context.Context, req *model.AdminCategoryDeleteRequest) error {
	ret := _mock.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for CategoryDelete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *model.AdminCategoryDeleteRequest) error); ok {
		r0 = returnFunc(ctx, req)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIAdminProductService_CategoryDelete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CategoryDelete'
type MockIAdminProductService_CategoryDelete_Call struct {
	*mock.Call
}

// CategoryDelete is a helper method to define mock.On call
//   - ctx context.Context
//   - req *model.AdminCategoryDeleteRequest
func (_e *MockIAdminProductService_Expecter) CategoryDelete(ctx any, req any) *MockIAdminProductService_CategoryDelete_Call {
	return &MockIAdminProductService_CategoryDelete_Call{Call: _e.mock.On("CategoryDelete", ctx, req)}
}

func (_c *MockIAdminProductService_CategoryDelete_Call) Run(run func(ctx context.Context, req *model.AdminCategoryDeleteRequest)) *MockIAdminProductService_CategoryDelete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *model.AdminCategoryDeleteRequest
		if args[1] != nil {
			arg1 = args[1].(*model.AdminCategoryDeleteRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIAdminProductService_CategoryDelete_Call) Return(err error) *MockIAdminProductService_CategoryDelete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIAdminProductService_CategoryDelete_Call) RunAndReturn(run func(ctx context.Context, req *model.AdminCategoryDeleteRequest) error) *MockIAdminProductService_CategoryDelete_Call {
	_c.Call.Return(run)
	return _c
}

// CategoryList provides a mock function for the type MockIAdminProductService
func (_mock *MockIAdminProductService) CategoryList(ctx context.Context, req *model.AdminCategoryListRequest) (*model.AdminCategoryListResponse, error) {
	ret := _mock.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for CategoryList")
	}

	var r0 *model.AdminCategoryListResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *model.AdminCategoryListRequest) (*model.AdminCategoryListResponse, error)); ok {
		return returnFunc(ctx, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *model.AdminCategoryListRequest) *model.AdminCategoryListResponse); ok {
		r0 = returnFunc(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.AdminCategoryListResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *model.AdminCategoryListRequest) error); ok {
		r1 = returnFunc(ctx, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIAdminProductService_CategoryList_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CategoryList'
type MockIAdminProductService_CategoryList_Call struct {
	*mock.Call
}

// CategoryList is a helper method to define mock.On call
//   - ctx context.Context
//   - req *model.AdminCategoryListRequest
func (_e *MockIAdminProductService_Expecter) CategoryList(ctx any, req any) *MockIAdminProductService_CategoryList_Call {
	return &MockIAdminProductService_CategoryList_Call{Call: _e.mock.On("CategoryList", ctx, req)}
}

func (_c *MockIAdminProductService_CategoryList_Call) Run(run func(ctx context.Context, req *model.AdminCategoryListRequest)) *MockIAdminProductService_CategoryList_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *model.AdminCategoryListRequest
		if args[1] != nil {
			arg1 = args[1].(*model.AdminCategoryListRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIAdminProductService_CategoryList_Call) Return(adminCategoryListResponse *model.AdminCategoryListResponse, err error) *MockIAdminProductService_CategoryList_Call {
	_c.Call.Return(adminCategoryListResponse, err)
	return _c
}

func (_c *MockIAdminProductService_CategoryList_Call) RunAndReturn(run func(ctx context.Context, req *model.AdminCategoryListRequest) (*model.AdminCategoryListResponse, error)) *MockIAdminProductService_CategoryList_Call {
	_c.Call.Return(run)
	return _c
}

// CategoryUpdate provides a mock function for the type MockIAdminProductService
func (_mock *MockIAdminProductService) CategoryUpdate(ctx context.Context, req *model.AdminCategoryUpdateRequest) (*model.AdminCategoryResponse, error) {
	ret := _mock.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for CategoryUpdate")
	}

	var r0 *model.AdminCategoryResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *model.AdminCategoryUpdateRequest) (*model.AdminCategoryResponse, error)); ok {
		return returnFunc(ctx, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *model.AdminCategoryUpdateRequest) *model.AdminCategoryResponse); ok {
		r0 = returnFunc(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.AdminCategoryResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *model.AdminCategoryUpdateRequest) error); ok {
		r1 = returnFunc(ctx, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIAdminProductService_CategoryUpdate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CategoryUpdate'
type MockIAdminProductService_CategoryUpdate_Call struct {
	*mock.Call
}

// CategoryUpdate is a helper method to define mock.On call
//   - ctx context.Context
//   - req *model.AdminCategoryUpdateRequest
func (_e *MockIAdminProductService_Expecter) CategoryUpdate(ctx any, req any) *MockIAdminProductService_CategoryUpdate_Call {
	return &MockIAdminProductService_CategoryUpdate_Call{Call: _e.mock.On("CategoryUpdate", ctx, req)}
}

func (_c *MockIAdminProductService_CategoryUpdate_Call) Run(run func(ctx context.Context, req *model.AdminCategoryUpdateRequest)) *MockIAdminProductService_CategoryUpdate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *model.AdminCategoryUpdateRequest
		if args[1] != nil {
			arg1 = args[1].(*model.AdminCategoryUpdateRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIAdminProductService_CategoryUpdate_Call) Return(adminCategoryResponse *model.AdminCategoryResponse, err error) *MockIAdminProductService_CategoryUpdate_Call {
	_c.Call.Return(adminCategoryResponse, err)
	return _c
}

func (_c *MockIAdminProductService_CategoryUpdate_Call) RunAndReturn(run func(ctx context.Context, req *model.AdminCategoryUpdateRequest) (*model.AdminCategoryResponse, error)) *MockIAdminProductService_CategoryUpdate_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function for the type MockIAdminProductService
func (_mock *MockIAdminProductService) Create(ctx context.Context, req *model.AdminProductCreateRequest) (*model.AdminProductResponse, error) {
	ret := _mock.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *model.AdminProductResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *model.AdminProductCreateRequest) (*model.AdminProductResponse, error)); ok {
		return returnFunc(ctx, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *model.AdminProductCreateRequest) *model.AdminProductResponse); ok {
		r0 = returnFunc(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.AdminProductResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *model.AdminProductCreateRequest) error); ok {
		r1 = returnFunc(ctx, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIAdminProductService_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockIAdminProductService_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - req *model.AdminProductCreateRequest
func (_e *MockIAdminProductService_Expecter) Create(ctx any, req any) *MockIAdminProductService_Create_Call {
	return &MockIAdminProductService_Create_Call{Call: _e.mock.On("Create", ctx, req)}
}

func (_c *MockIAdminProductService_Create_Call) Run(run func(ctx context.Context, req *model.AdminProductCreateRequest)) *MockIAdminProductService_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *model.AdminProductCreateRequest
		if args[1] != nil {
			arg1 = args[1].(*model.AdminProductCreateRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIAdminProductService_Create_Call) Return(adminProductResponse *model.AdminProductResponse, err error) *MockIAdminProductService_Create_Call {
	_c.Call.Return(adminProductResponse, err)
	return _c
}

func (_c *MockIAdminProductService_Create_Call) RunAndReturn(run func(ctx context.Context, req *model.AdminProductCreateRequest) (*model.AdminProductResponse, error)) *MockIAdminProductService_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type MockIAdminProductService
func (_mock *MockIAdminProductService) Delete(ctx context.Context, req *model.AdminProductDeleteRequest) error {
	ret := _mock.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *model.AdminProductDeleteRequest) error); ok {
		r0 = returnFunc(ctx, req)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIAdminProductService_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockIAdminProductService_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - req *model.AdminProductDeleteRequest
func (_e *MockIAdminProductService_Expecter) Delete(ctx any, req any) *MockIAdminProductService_Delete_Call {
	return &MockIAdminProductService_Delete_Call{Call: _e.mock.On("Delete", ctx, req)}
}

func (_c *MockIAdminProductService_Delete_Call) Run(run func(ctx context.Context, req *model.AdminProductDeleteRequest)) *MockIAdminProductService_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *model.AdminProductDeleteRequest
		if args[1] != nil {
			arg1 = args[1].(*model.AdminProductDeleteRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIAdminProductService_Delete_Call) Return(err error) *MockIAdminProductService_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIAdminProductService_Delete_Call) RunAndReturn(run func(ctx context.Context, req *model.AdminProductDeleteRequest) error) *MockIAdminProductService_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Detail provides a mock function for the type MockIAdminProductService
func (_mock *MockIAdminProductService) Detail(ctx context.Context, req *model.AdminProductDetailRequest) (*model.AdminProductResponse, error) {
	ret := _mock.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for Detail")
	}

	var r0 *model.AdminProductResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *model.AdminProductDetailRequest) (*model.AdminProductResponse, error)); ok {
		return returnFunc(ctx, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *model.AdminProductDetailRequest) *model.AdminProductResponse); ok {
		r0 = returnFunc(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.AdminProductResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *model.AdminProductDetailRequest) error); ok {
		r1 = returnFunc(ctx, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIAdminProductService_Detail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Detail'
type MockIAdminProductService_Detail_Call struct {
	*mock.Call
}

// Detail is a helper method to define mock.On call
//   - ctx context.Context
//   - req *model.AdminProductDetailRequest
func (_e *MockIAdminProductService_Expecter) Detail(ctx any, req any) *MockIAdminProductService_Detail_Call {
	return &MockIAdminProductService_Detail_Call{Call: _e.mock.On("Detail", ctx, req)}
}

func (_c *MockIAdminProductService_Detail_Call) Run(run func(ctx context.Context, req *model.AdminProductDetailRequest)) *MockIAdminProductService_Detail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *model.AdminProductDetailRequest
		if args[1] != nil {
			arg1 = args[1].(*model.AdminProductDetailRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIAdminProductService_Detail_Call) Return(adminProductResponse *model.AdminProductResponse, err error) *MockIAdminProductService_Detail_Call {
	_c.Call.Return(adminProductResponse, err)
	return _c
}

func (_c *MockIAdminProductService_Detail_Call) RunAndReturn(run func(ctx context.Context, req *model.AdminProductDetailRequest) (*model.AdminProductResponse, error)) *MockIAdminProductService_Detail_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function for the type MockIAdminProductService
func (_mock *MockIAdminProductService) List(ctx context.Context, req *model.AdminProductListRequest) (*model.AdminProductListResponse, error) {
	ret := _mock.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 *model.AdminProductListResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *model.AdminProductListRequest) (*model.AdminProductListResponse, error)); ok {
		return returnFunc(ctx, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *model.AdminProductListRequest) *model.AdminProductListResponse); ok {
		r0 = returnFunc(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.AdminProductListResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *model.AdminProductListRequest) error); ok {
		r1 = returnFunc(ctx, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIAdminProductService_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockIAdminProductService_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - req *model.AdminProductListRequest
func (_e *MockIAdminProductService_Expecter) List(ctx any, req any) *MockIAdminProductService_List_Call {
	return &MockIAdminProductService_List_Call{Call: _e.mock.On("List", ctx, req)}
}

func (_c *MockIAdminProductService_List_Call) Run(run func(ctx context.Context, req *model.AdminProductListRequest)) *MockIAdminProductService_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *model.AdminProductListRequest
		if args[1] != nil {
			arg1 = args[1].(*model.AdminProductListRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIAdminProductService_List_Call) Return(adminProductListResponse *model.AdminProductListResponse, err error) *MockIAdminProductService_List_Call {
	_c.Call.Return(adminProductListResponse, err)
	return _c
}

func (_c *MockIAdminProductService_List_Call) RunAndReturn(run func(ctx context.Context, req *model.AdminProductListRequest) (*model.AdminProductListResponse, error)) *MockIAdminProductService_List_Call {
	_c.Call.Return(run)
	return _c
}

// TagCreate provides a mock function for the type MockIAdminProductService
func (_mock *MockIAdminProductService) TagCreate(ctx context.Context, req *model.AdminTagCreateRequest) (*model.AdminTagResponse, error) {
	ret := _mock.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for TagCreate")
	}

	var r0 *model.AdminTagResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *model.AdminTagCreateRequest) (*model.AdminTagResponse, error)); ok {
		return returnFunc(ctx, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *model.AdminTagCreateRequest) *model.AdminTagResponse); ok {
		r0 = returnFunc(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.AdminTagResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *model.AdminTagCreateRequest) error); ok {
		r1 = returnFunc(ctx, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIAdminProductService_TagCreate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'TagCreate'
type MockIAdminProductService_TagCreate_Call struct {
	*mock.Call
}

// TagCreate is a helper method to define mock.On call
//   - ctx context.Context
//   - req *model.AdminTagCreateRequest
func (_e *MockIAdminProductService_Expecter) TagCreate(ctx any, req any) *MockIAdminProductService_TagCreate_Call {
	return &MockIAdminProductService_TagCreate_Call{Call: _e.mock.On("TagCreate", ctx, req)}
}

func (_c *MockIAdminProductService_TagCreate_Call) Run(run func(ctx context.Context, req *model.AdminTagCreateRequest)) *MockIAdminProductService_TagCreate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *model.AdminTagCreateRequest
		if args[1] != nil {
			arg1 = args[1].(*model.AdminTagCreateRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIAdminProductService_TagCreate_Call) Return(adminTagResponse *model.AdminTagResponse, err error) *MockIAdminProductService_TagCreate_Call {
	_c.Call.Return(adminTagResponse, err)
	return _c
}

func (_c *MockIAdminProductService_TagCreate_Call) RunAndReturn(run func(ctx context.Context, req *model.AdminTagCreateRequest) (*model.AdminTagResponse, error)) *MockIAdminProductService_TagCreate_Call {
	_c.Call.Return(run)
	return _c
}

// TagDelete provides a mock function for the type MockIAdminProductService
func (_mock *MockIAdminProductService) TagDelete(ctx context.Context, req *model.AdminTagDeleteRequest) error {
	ret := _mock.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for TagDelete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *model.AdminTagDeleteRequest) error); ok {
		r0 = returnFunc(ctx, req)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIAdminProductService_TagDelete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'TagDelete'
type MockIAdminProductService_TagDelete_Call struct {
	*mock.Call
}

// TagDelete is a helper method to define mock.On call
//   - ctx context.Context
//   - req *model.AdminTagDeleteRequest
func (_e *MockIAdminProductService_Expecter) TagDelete(ctx any, req any) *MockIAdminProductService_TagDelete_Call {
	return &MockIAdminProductService_TagDelete_Call{Call: _e.mock.On("TagDelete", ctx, req)}
}

func (_c *MockIAdminProductService_TagDelete_Call) Run(run func(ctx context.Context, req *model.AdminTagDeleteRequest)) *MockIAdminProductService_TagDelete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *model.AdminTagDeleteRequest
		if args[1] != nil {
			arg1 = args[1].(*model.AdminTagDeleteRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIAdminProductService_TagDelete_Call) Return(err error) *MockIAdminProductService_TagDelete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIAdminProductService_TagDelete_Call) RunAndReturn(run func(ctx context.Context, req *model.AdminTagDeleteRequest) error) *MockIAdminProductService_TagDelete_Call {
	_c.Call.Return(run)
	return _c
}

// TagList provides a mock function for the type MockIAdminProductService
func (_mock *MockIAdminProductService) TagList(ctx context.Context, req *model.AdminTagListRequest) (*model.AdminTagListResponse, error) {
	ret := _mock.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for TagList")
	}

	var r0 *model.AdminTagListResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *model.AdminTagListRequest) (*model.AdminTagListResponse, error)); ok {
		return returnFunc(ctx, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *model.AdminTagListRequest) *model.AdminTagListResponse); ok {
		r0 = returnFunc(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.AdminTagListResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *model.AdminTagListRequest) error); ok {
		r1 = returnFunc(ctx, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIAdminProductService_TagList_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'TagList'
type MockIAdminProductService_TagList_Call struct {
	*mock.Call
}

// TagList is a helper method to define mock.On call
//   - ctx context.Context
//   - req *model.AdminTagListRequest
func (_e *MockIAdminProductService_Expecter) TagList(ctx any, req any) *MockIAdminProductService_TagList_Call {
	return &MockIAdminProductService_TagList_Call{Call: _e.mock.On("TagList", ctx, req)}
}

func (_c *MockIAdminProductService_TagList_Call) Run(run func(ctx context.Context, req *model.AdminTagListRequest)) *MockIAdminProductService_TagList_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *model.AdminTagListRequest
		if args[1] != nil {
			arg1 = args[1].(*model.AdminTagListRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIAdminProductService_TagList_Call) Return(adminTagListResponse *model.AdminTagListResponse, err error) *MockIAdminProductService_TagList_Call {
	_c.Call.Return(adminTagListResponse, err)
	return _c
}

func (_c *MockIAdminProductService_TagList_Call) RunAndReturn(run func(ctx context.Context, req *model.AdminTagListRequest) (*model.AdminTagListResponse, error)) *MockIAdminProductService_TagList_Call {
	_c.Call.Return(run)
	return _c
}

// TagUpdate provides a mock function for the type MockIAdminProductService
func (_mock *MockIAdminProductService) TagUpdate(ctx context.Context, req *model.AdminTagUpdateRequest) (*model.AdminTagResponse, error) {
	ret := _mock.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for TagUpdate")
	}

	var r0 *model.AdminTagResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *model.AdminTagUpdateRequest) (*model.AdminTagResponse, error)); ok {
		return returnFunc(ctx, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *model.AdminTagUpdateRequest) *model.AdminTagResponse); ok {
		r0 = returnFunc(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.AdminTagResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *model.AdminTagUpdateRequest) error); ok {
		r1 = returnFunc(ctx, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIAdminProductService_TagUpdate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'TagUpdate'
type MockIAdminProductService_TagUpdate_Call struct {
	*mock.Call
}

// TagUpdate is a helper method to define mock.On call
//   - ctx context.Context
//   - req *model.AdminTagUpdateRequest
func (_e *MockIAdminProductService_Expecter) TagUpdate(ctx any, req any) *MockIAdminProductService_TagUpdate_Call {
	return &MockIAdminProductService_TagUpdate_Call{Call: _e.mock.On("TagUpdate", ctx, req)}
}

func (_c *MockIAdminProductService_TagUpdate_Call) Run(run func(ctx context.Context, req *model.AdminTagUpdateRequest)) *MockIAdminProductService_TagUpdate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *model.AdminTagUpdateRequest
		if args[1] != nil {
			arg1 = args[1].(*model.AdminTagUpdateRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIAdminProductService_TagUpdate_Call) Return(adminTagResponse *model.AdminTagResponse, err error) *MockIAdminProductService_TagUpdate_Call {
	_c.Call.Return(adminTagResponse, err)
	return _c
}

func (_c *MockIAdminProductService_TagUpdate_Call) RunAndReturn(run func(ctx context.Context, req *model.AdminTagUpdateRequest) (*model.AdminTagResponse, error)) *MockIAdminProductService_TagUpdate_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type MockIAdminProductService
func (_mock *MockIAdminProductService) Update(ctx context.Context, req *model.AdminProductUpdateRequest) (*model.AdminProductResponse, error) {
	ret := _mock.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 *model.AdminProductResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *model.AdminProductUpdateRequest) (*model.AdminProductResponse, error)); ok {
		return returnFunc(ctx, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *model.AdminProductUpdateRequest) *model.AdminProductResponse); ok {
		r0 = returnFunc(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.AdminProductResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *model.AdminProductUpdateRequest) error); ok {
		r1 = returnFunc(ctx, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIAdminProductService_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockIAdminProductService_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - req *model.AdminProductUpdateRequest
func (_e *MockIAdminProductService_Expecter) Update(ctx any, req any) *MockIAdminProductService_Update_Call {
	return &MockIAdminProductService_Update_Call{Call: _e.mock.On("Update", ctx, req)}
}

func (_c *MockIAdminProductService_Update_Call) Run(run func(ctx context.Context, req *model.AdminProductUpdateRequest)) *MockIAdminProductService_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *model.AdminProductUpdateRequest
		if args[1] != nil {
			arg1 = args[1].(*model.AdminProductUpdateRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIAdminProductService_Update_Call) Return(adminProductResponse *model.AdminProductResponse, err error) *MockIAdminProductService_Update_Call {
	_c.Call.Return(adminProductResponse, err)
	return _c
}

func (_c *MockIAdminProductService_Update_Call) RunAndReturn(run func(ctx context.Context, req *model.AdminProductUpdateRequest) (*model.AdminProductResponse, error)) *MockIAdminProductService_Update_Call {
	_c.Call.Return(run)
	return _c
}
