// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package service

import (
	"context"

	mock "github.com/stretchr/testify/mock"
	"github.com/wigata-intech/logres/internal/shared/model"
)

// NewMockIAdminOrderService creates a new instance of MockIAdminOrderService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIAdminOrderService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIAdminOrderService {
	mock := &MockIAdminOrderService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockIAdminOrderService is an autogenerated mock type for the IAdminOrderService type
type MockIAdminOrderService struct {
	mock.Mock
}

type MockIAdminOrderService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIAdminOrderService) EXPECT() *MockIAdminOrderService_Expecter {
	return &MockIAdminOrderService_Expecter{mock: &_m.Mock}
}

// CartDetail provides a mock function for the type MockIAdminOrderService
func (_mock *MockIAdminOrderService) CartDetail(ctx context.Context, req *model.AdminCartDetailRequest) (*model.AdminCartResponse, error) {
	ret := _mock.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for CartDetail")
	}

	var r0 *model.AdminCartResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *model.AdminCartDetailRequest) (*model.AdminCartResponse, error)); ok {
		return returnFunc(ctx, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *model.AdminCartDetailRequest) *model.AdminCartResponse); ok {
		r0 = returnFunc(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.AdminCartResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *model.AdminCartDetailRequest) error); ok {
		r1 = returnFunc(ctx, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIAdminOrderService_CartDetail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CartDetail'
type MockIAdminOrderService_CartDetail_Call struct {
	*mock.Call
}

// CartDetail is a helper method to define mock.On call
//   - ctx context.Context
//   - req *model.AdminCartDetailRequest
func (_e *MockIAdminOrderService_Expecter) CartDetail(ctx any, req any) *MockIAdminOrderService_CartDetail_Call {
	return &MockIAdminOrderService_CartDetail_Call{Call: _e.mock.On("CartDetail", ctx, req)}
}

func (_c *MockIAdminOrderService_CartDetail_Call) Run(run func(ctx context.Context, req *model.AdminCartDetailRequest)) *MockIAdminOrderService_CartDetail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *model.AdminCartDetailRequest
		if args[1] != nil {
			arg1 = args[1].(*model.AdminCartDetailRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIAdminOrderService_CartDetail_Call) Return(adminCartResponse *model.AdminCartResponse, err error) *MockIAdminOrderService_CartDetail_Call {
	_c.Call.Return(adminCartResponse, err)
	return _c
}

func (_c *MockIAdminOrderService_CartDetail_Call) RunAndReturn(run func(ctx context.Context, req *model.AdminCartDetailRequest) (*model.AdminCartResponse, error)) *MockIAdminOrderService_CartDetail_Call {
	_c.Call.Return(run)
	return _c
}

// CartList provides a mock function for the type MockIAdminOrderService
func (_mock *MockIAdminOrderService) CartList(ctx context.Context, req *model.AdminCartListRequest) (*model.AdminCartListResponse, error) {
	ret := _mock.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for CartList")
	}

	var r0 *model.AdminCartListResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *model.AdminCartListRequest) (*model.AdminCartListResponse, error)); ok {
		return returnFunc(ctx, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *model.AdminCartListRequest) *model.AdminCartListResponse); ok {
		r0 = returnFunc(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.AdminCartListResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *model.AdminCartListRequest) error); ok {
		r1 = returnFunc(ctx, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIAdminOrderService_CartList_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CartList'
type MockIAdminOrderService_CartList_Call struct {
	*mock.Call
}

// CartList is a helper method to define mock.On call
//   - ctx context.Context
//   - req *model.AdminCartListRequest
func (_e *MockIAdminOrderService_Expecter) CartList(ctx any, req any) *MockIAdminOrderService_CartList_Call {
	return &MockIAdminOrderService_CartList_Call{Call: _e.mock.On("CartList", ctx, req)}
}

func (_c *MockIAdminOrderService_CartList_Call) Run(run func(ctx context.Context, req *model.AdminCartListRequest)) *MockIAdminOrderService_CartList_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *model.AdminCartListRequest
		if args[1] != nil {
			arg1 = args[1].(*model.AdminCartListRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIAdminOrderService_CartList_Call) Return(adminCartListResponse *model.AdminCartListResponse, err error) *MockIAdminOrderService_CartList_Call {
	_c.Call.Return(adminCartListResponse, err)
	return _c
}

func (_c *MockIAdminOrderService_CartList_Call) RunAndReturn(run func(ctx context.Context, req *model.AdminCartListRequest) (*model.AdminCartListResponse, error)) *MockIAdminOrderService_CartList_Call {
	_c.Call.Return(run)
	return _c
}

// Detail provides a mock function for the type MockIAdminOrderService
func (_mock *MockIAdminOrderService) Detail(ctx context.Context, req *model.AdminOrderDetailRequest) (*model.AdminOrderResponse, error) {
	ret := _mock.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for Detail")
	}

	var r0 *model.AdminOrderResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *model.AdminOrderDetailRequest) (*model.AdminOrderResponse, error)); ok {
		return returnFunc(ctx, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *model.AdminOrderDetailRequest) *model.AdminOrderResponse); ok {
		r0 = returnFunc(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.AdminOrderResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *model.AdminOrderDetailRequest) error); ok {
		r1 = returnFunc(ctx, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIAdminOrderService_Detail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Detail'
type MockIAdminOrderService_Detail_Call struct {
	*mock.Call
}

// Detail is a helper method to define mock.On call
//   - ctx context.Context
//   - req *model.AdminOrderDetailRequest
func (_e *MockIAdminOrderService_Expecter) Detail(ctx any, req any) *MockIAdminOrderService_Detail_Call {
	return &MockIAdminOrderService_Detail_Call{Call: _e.mock.On("Detail", ctx, req)}
}

func (_c *MockIAdminOrderService_Detail_Call) Run(run func(ctx context.Context, req *model.AdminOrderDetailRequest)) *MockIAdminOrderService_Detail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *model.AdminOrderDetailRequest
		if args[1] != nil {
			arg1 = args[1].(*model.AdminOrderDetailRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIAdminOrderService_Detail_Call) Return(adminOrderResponse *model.AdminOrderResponse, err error) *MockIAdminOrderService_Detail_Call {
	_c.Call.Return(adminOrderResponse, err)
	return _c
}

func (_c *MockIAdminOrderService_Detail_Call) RunAndReturn(run func(ctx context.Context, req *model.AdminOrderDetailRequest) (*model.AdminOrderResponse, error)) *MockIAdminOrderService_Detail_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function for the type MockIAdminOrderService
func (_mock *MockIAdminOrderService) List(ctx context.Context, req *model.AdminOrderListRequest) (*model.AdminOrderListResponse, error) {
	ret := _mock.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 *model.AdminOrderListResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *model.AdminOrderListRequest) (*model.AdminOrderListResponse, error)); ok {
		return returnFunc(ctx, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *model.AdminOrderListRequest) *model.AdminOrderListResponse); ok {
		r0 = returnFunc(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.AdminOrderListResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *model.AdminOrderListRequest) error); ok {
		r1 = returnFunc(ctx, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIAdminOrderService_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockIAdminOrderService_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - req *model.AdminOrderListRequest
func (_e *MockIAdminOrderService_Expecter) List(ctx any, req any) *MockIAdminOrderService_List_Call {
	return &MockIAdminOrderService_List_Call{Call: _e.mock.On("List", ctx, req)}
}

func (_c *MockIAdminOrderService_List_Call) Run(run func(ctx context.Context, req *model.AdminOrderListRequest)) *MockIAdminOrderService_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *model.AdminOrderListRequest
		if args[1] != nil {
			arg1 = args[1].(*model.AdminOrderListRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIAdminOrderService_List_Call) Return(adminOrderListResponse *model.AdminOrderListResponse, err error) *MockIAdminOrderService_List_Call {
	_c.Call.Return(adminOrderListResponse, err)
	return _c
}

func (_c *MockIAdminOrderService_List_Call) RunAndReturn(run func(ctx context.Context, req *model.AdminOrderListRequest) (*model.AdminOrderListResponse, error)) *MockIAdminOrderService_List_Call {
	_c.Call.Return(run)
	return _c
}

// Process provides a mock function for the type MockIAdminOrderService
func (_mock *MockIAdminOrderService) Process(ctx context.Context, req *model.AdminOrderProcessRequest) (*model.AdminOrderResponse, error) {
	ret := _mock.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for Process")
	}

	var r0 *model.AdminOrderResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *model.AdminOrderProcessRequest) (*model.AdminOrderResponse, error)); ok {
		return returnFunc(ctx, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *model.AdminOrderProcessRequest) *model.AdminOrderResponse); ok {
		r0 = returnFunc(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.AdminOrderResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *model.AdminOrderProcessRequest) error); ok {
		r1 = returnFunc(ctx, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIAdminOrderService_Process_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Process'
type MockIAdminOrderService_Process_Call struct {
	*mock.Call
}

// Process is a helper method to define mock.On call
//   - ctx context.Context
//   - req *model.AdminOrderProcessRequest
func (_e *MockIAdminOrderService_Expecter) Process(ctx any, req any) *MockIAdminOrderService_Process_Call {
	return &MockIAdminOrderService_Process_Call{Call: _e.mock.On("Process", ctx, req)}
}

func (_c *MockIAdminOrderService_Process_Call) Run(run func(ctx context.Context, req *model.AdminOrderProcessRequest)) *MockIAdminOrderService_Process_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *model.AdminOrderProcessRequest
		if args[1] != nil {
			arg1 = args[1].(*model.AdminOrderProcessRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIAdminOrderService_Process_Call) Return(adminOrderResponse *model.AdminOrderResponse, err error) *MockIAdminOrderService_Process_Call {
	_c.Call.Return(adminOrderResponse, err)
	return _c
}

func (_c *MockIAdminOrderService_Process_Call) RunAndReturn(run func(ctx context.Context, req *model.AdminOrderProcessRequest) (*model.AdminOrderResponse, error)) *MockIAdminOrderService_Process_Call {
	_c.Call.Return(run)
	return _c
}
