// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package service

import (
	"context"

	mock "github.com/stretchr/testify/mock"
	"github.com/wigata-intech/logres/internal/shared/model"
)

// NewMockICartService creates a new instance of MockICartService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockICartService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockICartService {
	mock := &MockICartService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockICartService is an autogenerated mock type for the ICartService type
type MockICartService struct {
	mock.Mock
}

type MockICartService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockICartService) EXPECT() *MockICartService_Expecter {
	return &MockICartService_Expecter{mock: &_m.Mock}
}

// Delete provides a mock function for the type MockICartService
func (_mock *MockICartService) Delete(ctx context.Context, req *model.CartDeleteRequest) error {
	ret := _mock.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *model.CartDeleteRequest) error); ok {
		r0 = returnFunc(ctx, req)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockICartService_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockICartService_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - req *model.CartDeleteRequest
func (_e *MockICartService_Expecter) Delete(ctx any, req any) *MockICartService_Delete_Call {
	return &MockICartService_Delete_Call{Call: _e.mock.On("Delete", ctx, req)}
}

func (_c *MockICartService_Delete_Call) Run(run func(ctx context.Context, req *model.CartDeleteRequest)) *MockICartService_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *model.CartDeleteRequest
		if args[1] != nil {
			arg1 = args[1].(*model.CartDeleteRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockICartService_Delete_Call) Return(err error) *MockICartService_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockICartService_Delete_Call) RunAndReturn(run func(ctx context.Context, req *model.CartDeleteRequest) error) *MockICartService_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Insert provides a mock function for the type MockICartService
func (_mock *MockICartService) Insert(ctx context.Context, req *model.CartInsertRequest) (*model.CartResponse, error) {
	ret := _mock.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for Insert")
	}

	var r0 *model.CartResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *model.CartInsertRequest) (*model.CartResponse, error)); ok {
		return returnFunc(ctx, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *model.CartInsertRequest) *model.CartResponse); ok {
		r0 = returnFunc(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.CartResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *model.CartInsertRequest) error); ok {
		r1 = returnFunc(ctx, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockICartService_Insert_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Insert'
type MockICartService_Insert_Call struct {
	*mock.Call
}

// Insert is a helper method to define mock.On call
//   - ctx context.Context
//   - req *model.CartInsertRequest
func (_e *MockICartService_Expecter) Insert(ctx any, req any) *MockICartService_Insert_Call {
	return &MockICartService_Insert_Call{Call: _e.mock.On("Insert", ctx, req)}
}

func (_c *MockICartService_Insert_Call) Run(run func(ctx context.Context, req *model.CartInsertRequest)) *MockICartService_Insert_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *model.CartInsertRequest
		if args[1] != nil {
			arg1 = args[1].(*model.CartInsertRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockICartService_Insert_Call) Return(cartResponse *model.CartResponse, err error) *MockICartService_Insert_Call {
	_c.Call.Return(cartResponse, err)
	return _c
}

func (_c *MockICartService_Insert_Call) RunAndReturn(run func(ctx context.Context, req *model.CartInsertRequest) (*model.CartResponse, error)) *MockICartService_Insert_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function for the type MockICartService
func (_mock *MockICartService) List(ctx context.Context, req *model.CartListRequest) (*model.CartListResponse, error) {
	ret := _mock.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 *model.CartListResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *model.CartListRequest) (*model.CartListResponse, error)); ok {
		return returnFunc(ctx, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *model.CartListRequest) *model.CartListResponse); ok {
		r0 = returnFunc(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.CartListResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *model.CartListRequest) error); ok {
		r1 = returnFunc(ctx, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockICartService_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockICartService_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - req *model.CartListRequest
func (_e *MockICartService_Expecter) List(ctx any, req any) *MockICartService_List_Call {
	return &MockICartService_List_Call{Call: _e.mock.On("List", ctx, req)}
}

func (_c *MockICartService_List_Call) Run(run func(ctx context.Context, req *model.CartListRequest)) *MockICartService_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *model.CartListRequest
		if args[1] != nil {
			arg1 = args[1].(*model.CartListRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockICartService_List_Call) Return(cartListResponse *model.CartListResponse, err error) *MockICartService_List_Call {
	_c.Call.Return(cartListResponse, err)
	return _c
}

func (_c *MockICartService_List_Call) RunAndReturn(run func(ctx context.Context, req *model.CartListRequest) (*model.CartListResponse, error)) *MockICartService_List_Call {
	_c.Call.Return(run)
	return _c
}

// Patch provides a mock function for the type MockICartService
func (_mock *MockICartService) Patch(ctx context.Context, req *model.CartPatchRequest) (*model.CartResponse, error) {
	ret := _mock.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for Patch")
	}

	var r0 *model.CartResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *model.CartPatchRequest) (*model.CartResponse, error)); ok {
		return returnFunc(ctx, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *model.CartPatchRequest) *model.CartResponse); ok {
		r0 = returnFunc(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.CartResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *model.CartPatchRequest) error); ok {
		r1 = returnFunc(ctx, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockICartService_Patch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Patch'
type MockICartService_Patch_Call struct {
	*mock.Call
}

// Patch is a helper method to define mock.On call
//   - ctx context.Context
//   - req *model.CartPatchRequest
func (_e *MockICartService_Expecter) Patch(ctx any, req any) *MockICartService_Patch_Call {
	return &MockICartService_Patch_Call{Call: _e.mock.On("Patch", ctx, req)}
}

func (_c *MockICartService_Patch_Call) Run(run func(ctx context.Context, req *model.CartPatchRequest)) *MockICartService_Patch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *model.CartPatchRequest
		if args[1] != nil {
			arg1 = args[1].(*model.CartPatchRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockICartService_Patch_Call) Return(cartResponse *model.CartResponse, err error) *MockICartService_Patch_Call {
	_c.Call.Return(cartResponse, err)
	return _c
}

func (_c *MockICartService_Patch_Call) RunAndReturn(run func(ctx context.Context, req *model.CartPatchRequest) (*model.CartResponse, error)) *MockICartService_Patch_Call {
	_c.Call.Return(run)
	return _c
}
