// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package service

import (
	"context"

	mock "github.com/stretchr/testify/mock"
	"github.com/wigata-intech/logres/internal/shared/model"
)

// NewMockIOrderService creates a new instance of MockIOrderService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIOrderService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIOrderService {
	mock := &MockIOrderService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockIOrderService is an autogenerated mock type for the IOrderService type
type MockIOrderService struct {
	mock.Mock
}

type MockIOrderService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIOrderService) EXPECT() *MockIOrderService_Expecter {
	return &MockIOrderService_Expecter{mock: &_m.Mock}
}

// Check provides a mock function for the type MockIOrderService
func (_mock *MockIOrderService) Check(ctx context.Context, req *model.OrderCheckRequest) (*model.OrderResponse, error) {
	ret := _mock.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for Check")
	}

	var r0 *model.OrderResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *model.OrderCheckRequest) (*model.OrderResponse, error)); ok {
		return returnFunc(ctx, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *model.OrderCheckRequest) *model.OrderResponse); ok {
		r0 = returnFunc(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.OrderResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *model.OrderCheckRequest) error); ok {
		r1 = returnFunc(ctx, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIOrderService_Check_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Check'
type MockIOrderService_Check_Call struct {
	*mock.Call
}

// Check is a helper method to define mock.On call
//   - ctx context.Context
//   - req *model.OrderCheckRequest
func (_e *MockIOrderService_Expecter) Check(ctx any, req any) *MockIOrderService_Check_Call {
	return &MockIOrderService_Check_Call{Call: _e.mock.On("Check", ctx, req)}
}

func (_c *MockIOrderService_Check_Call) Run(run func(ctx context.Context, req *model.OrderCheckRequest)) *MockIOrderService_Check_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *model.OrderCheckRequest
		if args[1] != nil {
			arg1 = args[1].(*model.OrderCheckRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIOrderService_Check_Call) Return(orderResponse *model.OrderResponse, err error) *MockIOrderService_Check_Call {
	_c.Call.Return(orderResponse, err)
	return _c
}

func (_c *MockIOrderService_Check_Call) RunAndReturn(run func(ctx context.Context, req *model.OrderCheckRequest) (*model.OrderResponse, error)) *MockIOrderService_Check_Call {
	_c.Call.Return(run)
	return _c
}

// Checkout provides a mock function for the type MockIOrderService
func (_mock *MockIOrderService) Checkout(ctx context.Context, req *model.OrderCheckoutRequest) (*model.OrderCheckoutResponse, error) {
	ret := _mock.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for Checkout")
	}

	var r0 *model.OrderCheckoutResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *model.OrderCheckoutRequest) (*model.OrderCheckoutResponse, error)); ok {
		return returnFunc(ctx, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *model.OrderCheckoutRequest) *model.OrderCheckoutResponse); ok {
		r0 = returnFunc(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.OrderCheckoutResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *model.OrderCheckoutRequest) error); ok {
		r1 = returnFunc(ctx, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIOrderService_Checkout_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Checkout'
type MockIOrderService_Checkout_Call struct {
	*mock.Call
}

// Checkout is a helper method to define mock.On call
//   - ctx context.Context
//   - req *model.OrderCheckoutRequest
func (_e *MockIOrderService_Expecter) Checkout(ctx any, req any) *MockIOrderService_Checkout_Call {
	return &MockIOrderService_Checkout_Call{Call: _e.mock.On("Checkout", ctx, req)}
}

func (_c *MockIOrderService_Checkout_Call) Run(run func(ctx context.Context, req *model.OrderCheckoutRequest)) *MockIOrderService_Checkout_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *model.OrderCheckoutRequest
		if args[1] != nil {
			arg1 = args[1].(*model.OrderCheckoutRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIOrderService_Checkout_Call) Return(orderCheckoutResponse *model.OrderCheckoutResponse, err error) *MockIOrderService_Checkout_Call {
	_c.Call.Return(orderCheckoutResponse, err)
	return _c
}

func (_c *MockIOrderService_Checkout_Call) RunAndReturn(run func(ctx context.Context, req *model.OrderCheckoutRequest) (*model.OrderCheckoutResponse, error)) *MockIOrderService_Checkout_Call {
	_c.Call.Return(run)
	return _c
}
