// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package service

import (
	"context"

	mock "github.com/stretchr/testify/mock"
	"github.com/wigata-intech/logres/internal/shared/model"
)

// NewMockIProductService creates a new instance of MockIProductService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIProductService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIProductService {
	mock := &MockIProductService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockIProductService is an autogenerated mock type for the IProductService type
type MockIProductService struct {
	mock.Mock
}

type MockIProductService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIProductService) EXPECT() *MockIProductService_Expecter {
	return &MockIProductService_Expecter{mock: &_m.Mock}
}

// Detail provides a mock function for the type MockIProductService
func (_mock *MockIProductService) Detail(Ctx context.Context, req *model.ProductDetailRequest) (*model.ProductResponse, error) {
	ret := _mock.Called(Ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for Detail")
	}

	var r0 *model.ProductResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *model.ProductDetailRequest) (*model.ProductResponse, error)); ok {
		return returnFunc(Ctx, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *model.ProductDetailRequest) *model.ProductResponse); ok {
		r0 = returnFunc(Ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.ProductResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *model.ProductDetailRequest) error); ok {
		r1 = returnFunc(Ctx, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIProductService_Detail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Detail'
type MockIProductService_Detail_Call struct {
	*mock.Call
}

// Detail is a helper method to define mock.On call
//   - Ctx context.Context
//   - req *model.ProductDetailRequest
func (_e *MockIProductService_Expecter) Detail(Ctx any, req any) *MockIProductService_Detail_Call {
	return &MockIProductService_Detail_Call{Call: _e.mock.On("Detail", Ctx, req)}
}

func (_c *MockIProductService_Detail_Call) Run(run func(Ctx context.Context, req *model.ProductDetailRequest)) *MockIProductService_Detail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *model.ProductDetailRequest
		if args[1] != nil {
			arg1 = args[1].(*model.ProductDetailRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIProductService_Detail_Call) Return(productResponse *model.ProductResponse, err error) *MockIProductService_Detail_Call {
	_c.Call.Return(productResponse, err)
	return _c
}

func (_c *MockIProductService_Detail_Call) RunAndReturn(run func(Ctx context.Context, req *model.ProductDetailRequest) (*model.ProductResponse, error)) *MockIProductService_Detail_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function for the type MockIProductService
func (_mock *MockIProductService) List(ctx context.Context, req *model.ProductListRequest) (*model.ProductListResponse, error) {
	ret := _mock.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 *model.ProductListResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *model.ProductListRequest) (*model.ProductListResponse, error)); ok {
		return returnFunc(ctx, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *model.ProductListRequest) *model.ProductListResponse); ok {
		r0 = returnFunc(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.ProductListResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *model.ProductListRequest) error); ok {
		r1 = returnFunc(ctx, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIProductService_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockIProductService_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - req *model.ProductListRequest
func (_e *MockIProductService_Expecter) List(ctx any, req any) *MockIProductService_List_Call {
	return &MockIProductService_List_Call{Call: _e.mock.On("List", ctx, req)}
}

func (_c *MockIProductService_List_Call) Run(run func(ctx context.Context, req *model.ProductListRequest)) *MockIProductService_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *model.ProductListRequest
		if args[1] != nil {
			arg1 = args[1].(*model.ProductListRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIProductService_List_Call) Return(productListResponse *model.ProductListResponse, err error) *MockIProductService_List_Call {
	_c.Call.Return(productListResponse, err)
	return _c
}

func (_c *MockIProductService_List_Call) RunAndReturn(run func(ctx context.Context, req *model.ProductListRequest) (*model.ProductListResponse, error)) *MockIProductService_List_Call {
	_c.Call.Return(run)
	return _c
}
